// Spanish DGT Driving Vocabulary Data
// This file contains all the vocabulary terms for the DGT flashcard application

window.vocabularyData = [
  {
    word: "vehículo",
    translation: "vehicle",
    category: "noun",
    example: "El vehículo debe estar matriculado",
  },
  {
    word: "conductor",
    translation: "driver",
    category: "noun",
    example: "El conductor debe tener permiso de conducir",
  },
  {
    word: "peatón",
    translation: "pedestrian",
    category: "noun",
    example: "El peatón tiene prioridad en el paso de cebra",
  },
  {
    word: "carretera",
    translation: "road/highway",
    category: "noun",
    example: "La carretera está en buen estado",
  },
  {
    word: "cinturón",
    translation: "seatbelt",
    category: "noun",
    example: "Es obligatorio usar el cinturón de seguridad",
  },
  {
    word: "cruce",
    translation: "intersection/crossing",
    category: "noun",
    example: "Cuidado en el cruce de calles",
  },
  {
    word: "intersección",
    translation: "intersection",
    category: "noun",
    example: "La intersección está regulada por semáforos",
  },
  {
    word: "señal",
    translation: "sign/signal",
    category: "noun",
    example: "Respeta todas las señales de tráfico",
  },
  {
    word: "autovía",
    translation: "highway/dual carriageway",
    category: "noun",
    example: "La velocidad máxima en autovía es 120 km/h",
  },
  {
    word: "glorieta",
    translation: "roundabout",
    category: "noun",
    example: "Cede el paso al entrar en la glorieta",
  },
  {
    word: "permiso",
    translation: "license/permit",
    category: "noun",
    example: "Necesitas permiso de conducir válido",
  },
  {
    word: "matrícula",
    translation: "license plate/registration",
    category: "noun",
    example: "La matrícula debe estar visible",
  },
  {
    word: "carga",
    translation: "load/cargo",
    category: "noun",
    example: "La carga debe estar bien sujeta",
  },
  {
    word: "seguridad",
    translation: "safety/security",
    category: "noun",
    example: "La seguridad vial es fundamental",
  },
  {
    word: "accidente",
    translation: "accident",
    category: "noun",
    example: "Evita los accidentes conduciendo con prudencia",
  },
  {
    word: "normativa",
    translation: "regulations",
    category: "noun",
    example: "Cumple la normativa de tráfico",
  },
  {
    word: "agente",
    translation: "officer/agent",
    category: "noun",
    example: "El agente de tráfico dirige la circulación",
  },
  {
    word: "autoridad",
    translation: "authority",
    category: "noun",
    example: "Obedece a la autoridad competente",
  },
  {
    word: "túnel",
    translation: "tunnel",
    category: "noun",
    example: "Enciende las luces en el túnel",
  },
  {
    word: "velocidad",
    translation: "speed",
    category: "noun",
    example: "Respeta los límites de velocidad",
  },
  {
    word: "luz",
    translation: "light",
    category: "noun",
    example: "Usa las luces cuando sea necesario",
  },
  {
    word: "alumbrado",
    translation: "lighting",
    category: "noun",
    example: "El alumbrado público facilita la visión",
  },
  {
    word: "multa",
    translation: "fine",
    category: "noun",
    example: "Te pueden poner una multa por exceso de velocidad",
  },
  {
    word: "sanción",
    translation: "penalty/sanction",
    category: "noun",
    example: "La sanción puede incluir pérdida de puntos",
  },
  {
    word: "dirección",
    translation: "direction/steering",
    category: "noun",
    example: "Mantén la dirección correcta",
  },
  {
    word: "camión",
    translation: "truck",
    category: "noun",
    example: "Los camiones tienen limitaciones especiales",
  },
  {
    word: "motocicleta",
    translation: "motorcycle",
    category: "noun",
    example: "La motocicleta debe circular por el carril derecho",
  },
  {
    word: "pasajero",
    translation: "passenger",
    category: "noun",
    example: "Los pasajeros deben usar cinturón",
  },
  {
    word: "travesía",
    translation: "crossing/traverse",
    category: "noun",
    example: "Reduce la velocidad en travesías urbanas",
  },
  {
    word: "peligro",
    translation: "danger",
    category: "noun",
    example: "Señaliza el peligro con el triángulo",
  },
  {
    word: "calzada",
    translation: "roadway",
    category: "noun",
    example: "No pares en la calzada",
  },
  {
    word: "arcén",
    translation: "shoulder/hard shoulder",
    category: "noun",
    example: "Para en el arcén si es necesario",
  },
  {
    word: "carril",
    translation: "lane",
    category: "noun",
    example: "Mantente en tu carril",
  },
  {
    word: "documento",
    translation: "document",
    category: "noun",
    example: "Lleva siempre la documentación",
  },
  {
    word: "infracción",
    translation: "violation/offense",
    category: "noun",
    example: "Evita cometer infracciones",
  },
  {
    word: "usuario",
    translation: "user",
    category: "noun",
    example: "Todo usuario de la vía debe cumplir las normas",
  },
  {
    word: "vía",
    translation: "road/way",
    category: "noun",
    example: "La vía pública es de todos",
  },
  {
    word: "maniobra",
    translation: "maneuver",
    category: "noun",
    example: "Realiza la maniobra con precaución",
  },
  {
    word: "prioridad",
    translation: "priority",
    category: "noun",
    example: "Los peatones tienen prioridad",
  },
  {
    word: "obstáculo",
    translation: "obstacle",
    category: "noun",
    example: "Evita cualquier obstáculo en la vía",
  },
  {
    word: "conducir",
    translation: "to drive",
    category: "verb",
    example: "Saber conducir requiere práctica",
  },
  {
    word: "parar",
    translation: "to stop",
    category: "verb",
    example: "Debes parar en el semáforo rojo",
  },
  {
    word: "detener",
    translation: "to stop/halt",
    category: "verb",
    example: "El agente puede detener el vehículo",
  },
  {
    word: "girar",
    translation: "to turn",
    category: "verb",
    example: "Indica antes de girar",
  },
  {
    word: "adelantar",
    translation: "to overtake",
    category: "verb",
    example: "Solo adelanta cuando sea seguro",
  },
  {
    word: "ceder",
    translation: "to yield/give way",
    category: "verb",
    example: "Cede el paso a los peatones",
  },
  {
    word: "respetar",
    translation: "to respect/obey",
    category: "verb",
    example: "Respeta las señales de tráfico",
  },
  {
    word: "usar",
    translation: "to use",
    category: "verb",
    example: "Usa siempre el cinturón de seguridad",
  },
  {
    word: "encender",
    translation: "to turn on/light",
    category: "verb",
    example: "Enciende las luces si es necesario",
  },
  {
    word: "obligar",
    translation: "to obligate/force",
    category: "verb",
    example: "La ley obliga a usar casco",
  },
  {
    word: "prohibir",
    translation: "to prohibit/forbid",
    category: "verb",
    example: "Se prohíbe aparcar aquí",
  },
  {
    word: "permitir",
    translation: "to allow/permit",
    category: "verb",
    example: "No se permite circular a más de 50 km/h",
  },
  {
    word: "señalar",
    translation: "to signal/indicate",
    category: "verb",
    example: "Señala tus intenciones claramente",
  },
  {
    word: "rebasar",
    translation: "to exceed/overtake",
    category: "verb",
    example: "No rebases el límite de velocidad",
  },
  {
    word: "comprobar",
    translation: "to check/verify",
    category: "verb",
    example: "Comprueba el estado del vehículo",
  },
  {
    word: "avisar",
    translation: "to warn/notify",
    category: "verb",
    example: "Avisa con las luces de emergencia",
  },
  {
    word: "esperar",
    translation: "to wait",
    category: "verb",
    example: "Espera a que el semáforo se ponga verde",
  },
  {
    word: "reducir",
    translation: "to reduce",
    category: "verb",
    example: "Reduce la velocidad en curvas",
  },
  {
    word: "mantener",
    translation: "to maintain",
    category: "verb",
    example: "Mantén la distancia de seguridad",
  },
  {
    word: "circular",
    translation: "to circulate/drive",
    category: "verb",
    example: "Circula siempre por la derecha",
  },
  {
    word: "responder",
    translation: "to respond",
    category: "verb",
    example: "Responde rápido en emergencias",
  },
  {
    word: "iniciar",
    translation: "to start/begin",
    category: "verb",
    example: "Inicia la marcha con precaución",
  },
  {
    word: "detectar",
    translation: "to detect",
    category: "verb",
    example: "Detecta los peligros a tiempo",
  },
  {
    word: "interrumpir",
    translation: "to interrupt",
    category: "verb",
    example: "No interrumpas el paso de otros vehículos",
  },
  {
    word: "mostrar",
    translation: "to show",
    category: "verb",
    example: "Muestra la documentación si te la piden",
  },
  {
    word: "observar",
    translation: "to observe",
    category: "verb",
    example: "Observa bien antes de cambiar de carril",
  },
  {
    word: "controlar",
    translation: "to control",
    category: "verb",
    example: "Controla siempre tu vehículo",
  },
  {
    word: "colocar",
    translation: "to place/position",
    category: "verb",
    example: "Coloca el triángulo de emergencia",
  },
  {
    word: "salir",
    translation: "to exit/leave",
    category: "verb",
    example: "Sale del carril con cuidado",
  },
  {
    word: "entrar",
    translation: "to enter",
    category: "verb",
    example: "Entra en la autopista usando el carril de aceleración",
  },
  {
    word: "bloquear",
    translation: "to block",
    category: "verb",
    example: "No bloquees las intersecciones",
  },
  {
    word: "repetir",
    translation: "to repeat",
    category: "verb",
    example: "No repitas la misma infracción",
  },
  {
    word: "transitar",
    translation: "to transit/travel",
    category: "verb",
    example: "Transita con precaución por zonas escolares",
  },
  {
    word: "obstaculizar",
    translation: "to obstruct",
    category: "verb",
    example: "No obstaculices el tráfico",
  },
  {
    word: "cargar",
    translation: "to load",
    category: "verb",
    example: "Carga el vehículo correctamente",
  },
  {
    word: "desviar",
    translation: "to detour/divert",
    category: "verb",
    example: "Desvía el tráfico si hay obras",
  },
  {
    word: "atropellar",
    translation: "to run over",
    category: "verb",
    example: "Evita atropellar a los peatones",
  },
  {
    word: "cruzar",
    translation: "to cross",
    category: "verb",
    example: "Cruza la calle por el paso de peatones",
  },
  {
    word: "seguir",
    translation: "to follow/continue",
    category: "verb",
    example: "Sigue las indicaciones del agente",
  },
  {
    word: "dejar",
    translation: "to leave/let",
    category: "verb",
    example: "Deja espacio suficiente entre vehículos",
  },
  {
    word: "realizar",
    translation: "to carry out/perform",
    category: "verb",
    example: "Realiza las maniobras con seguridad",
  },
  {
    word: "presentar",
    translation: "to present/show",
    category: "verb",
    example: "Presenta la documentación cuando te la pidan",
  },
  {
    word: "advertir",
    translation: "to warn",
    category: "verb",
    example: "Advierte del peligro con las luces",
  },
  {
    word: "identificar",
    translation: "to identify",
    category: "verb",
    example: "Identifica las señales de tráfico",
  },
  {
    word: "garantizar",
    translation: "to guarantee",
    category: "verb",
    example: "Garantiza la seguridad de todos",
  },
  {
    word: "situar",
    translation: "to place/locate",
    category: "verb",
    example: "Sitúa el vehículo en el carril correcto",
  },
  {
    word: "recibir",
    translation: "to receive",
    category: "verb",
    example: "Recibe las instrucciones del examinador",
  },
  {
    word: "deber",
    translation: "must/should",
    category: "verb",
    example: "Debes respetar las normas",
  },
  {
    word: "procurar",
    translation: "to try/ensure",
    category: "verb",
    example: "Procura mantener la calma al volante",
  },
  {
    word: "obligatorio",
    translation: "mandatory/compulsory",
    category: "adjective",
    example: "Es obligatorio usar el cinturón",
  },
  {
    word: "prohibido",
    translation: "prohibited/forbidden",
    category: "adjective",
    example: "Está prohibido aparcar aquí",
  },
  {
    word: "permitido",
    translation: "allowed/permitted",
    category: "adjective",
    example: "Está permitido adelantar",
  },
  {
    word: "visible",
    translation: "visible",
    category: "adjective",
    example: "La matrícula debe ser visible",
  },
  {
    word: "seguro",
    translation: "safe/secure",
    category: "adjective",
    example: "Conduce de forma segura",
  },
  {
    word: "urbano",
    translation: "urban/city",
    category: "adjective",
    example: "En zona urbana la velocidad es 50 km/h",
  },
  {
    word: "interurbano",
    translation: "interurban/between cities",
    category: "adjective",
    example: "En carretera interurbana 90 km/h",
  },
  {
    word: "contrario",
    translation: "opposite/contrary",
    category: "adjective",
    example: "No circules en sentido contrario",
  },
  {
    word: "adecuado",
    translation: "adequate/appropriate",
    category: "adjective",
    example: "Mantén una velocidad adecuada",
  },
  {
    word: "máximo",
    translation: "maximum",
    category: "adjective",
    example: "Respeta la velocidad máxima",
  },
  {
    word: "mínimo",
    translation: "minimum",
    category: "adjective",
    example: "Mantén la distancia mínima",
  },
  {
    word: "anterior",
    translation: "previous/front",
    category: "adjective",
    example: "El vehículo anterior frena",
  },
  {
    word: "posterior",
    translation: "rear/back",
    category: "adjective",
    example: "Mira por el espejo posterior",
  },
  {
    word: "especial",
    translation: "special",
    category: "adjective",
    example: "Precaución especial con niños",
  },
  {
    word: "grave",
    translation: "serious/severe",
    category: "adjective",
    example: "Una infracción grave quita puntos",
  },
  {
    word: "leve",
    translation: "minor/light",
    category: "adjective",
    example: "Una falta leve tiene multa pequeña",
  },
  {
    word: "cercano",
    translation: "near/close",
    category: "adjective",
    example: "Mantente cercano al carril derecho",
  },
  {
    word: "claro",
    translation: "clear/bright",
    category: "adjective",
    example: "Conduce solo si tienes visión clara",
  },
  {
    word: "oscuro",
    translation: "dark",
    category: "adjective",
    example: "Enciende luces en tiempo oscuro",
  },
  {
    word: "vulnerable",
    translation: "vulnerable",
    category: "adjective",
    example: "Los ciclistas son usuarios vulnerables",
  },
  {
    word: "rápido",
    translation: "fast/quick",
    category: "adjective",
    example: "No seas demasiado rápido",
  },
  {
    word: "lento",
    translation: "slow",
    category: "adjective",
    example: "Ir muy lento también es peligroso",
  },
  {
    word: "paralelo",
    translation: "parallel",
    category: "adjective",
    example: "Aparca en paralelo a la acera",
  },
  {
    word: "recto",
    translation: "straight",
    category: "adjective",
    example: "Sigue recto hasta el semáforo",
  },
  {
    word: "legal",
    translation: "legal",
    category: "adjective",
    example: "Asegúrate de que todo sea legal",
  },
  {
    word: "ilegal",
    translation: "illegal",
    category: "adjective",
    example: "Aparcar en doble fila es ilegal",
  },
  {
    word: "principal",
    translation: "main/principal",
    category: "adjective",
    example: "Circula por la vía principal",
  },
  {
    word: "secundario",
    translation: "secondary",
    category: "adjective",
    example: "Cede paso desde vía secundaria",
  },
  {
    word: "peatonal",
    translation: "pedestrian",
    category: "adjective",
    example: "Respeta la zona peatonal",
  },
  {
    word: "motorizado",
    translation: "motorized",
    category: "adjective",
    example: "Vehículo motorizado necesita permiso",
  },
  {
    word: "encendido",
    translation: "on/lit",
    category: "adjective",
    example: "Mantén las luces encendidas",
  },
  {
    word: "apagado",
    translation: "off/turned off",
    category: "adjective",
    example: "Motor apagado en semáforos largos",
  },
  {
    word: "responsable",
    translation: "responsible",
    category: "adjective",
    example: "Sé responsable al volante",
  },
  {
    word: "prudente",
    translation: "prudent/careful",
    category: "adjective",
    example: "Conduce de manera prudente",
  },
  {
    word: "peligroso",
    translation: "dangerous",
    category: "adjective",
    example: "Adelantar aquí es peligroso",
  },
  {
    word: "frecuente",
    translation: "frequent",
    category: "adjective",
    example: "Son frecuentes los controles",
  },
  {
    word: "eventual",
    translation: "occasional/possible",
    category: "adjective",
    example: "Posible hielo en la calzada",
  },
  {
    word: "habitual",
    translation: "usual/habitual",
    category: "adjective",
    example: "Usa tu ruta habitual",
  },
  {
    word: "completo",
    translation: "complete/full",
    category: "adjective",
    example: "Haz una revisión completa",
  },
  {
    word: "parcial",
    translation: "partial",
    category: "adjective",
    example: "Visibilidad parcial por niebla",
  },
  {
    word: "público",
    translation: "public",
    category: "adjective",
    example: "Respeta el transporte público",
  },
  {
    word: "privado",
    translation: "private",
    category: "adjective",
    example: "Propiedad privada, no aparcar",
  },
  {
    word: "exterior",
    translation: "exterior/outside",
    category: "adjective",
    example: "Limpia los espejos exteriores",
  },
  {
    word: "interior",
    translation: "interior/inside",
    category: "adjective",
    example: "Ajusta el espejo interior",
  },
  {
    word: "fijo",
    translation: "fixed/stationary",
    category: "adjective",
    example: "Obstáculo fijo en la vía",
  },
  {
    word: "móvil",
    translation: "mobile/moving",
    category: "adjective",
    example: "Precaución con obstáculos móviles",
  },
  {
    word: "estrecho",
    translation: "narrow",
    category: "adjective",
    example: "Carretera estrecha, precaución",
  },
  {
    word: "ancho",
    translation: "wide",
    category: "adjective",
    example: "Carril ancho para adelantar",
  },
  {
    word: "elevado",
    translation: "elevated/high",
    category: "adjective",
    example: "Paso elevado para peatones",
  },
  {
    word: "bajo",
    translation: "low",
    category: "adjective",
    example: "Puente bajo, altura limitada",
  },
  {
    word: "normal",
    translation: "normal",
    category: "adjective",
    example: "Condiciones normales de tráfico",
  },
  {
    word: "excesivo",
    translation: "excessive",
    category: "adjective",
    example: "Velocidad excesiva es peligrosa",
  },
  {
    word: "ligero",
    translation: "light",
    category: "adjective",
    example: "Vehículo ligero hasta 3500 kg",
  },
  {
    word: "pesado",
    translation: "heavy",
    category: "adjective",
    example: "Vehículo pesado más de 3500 kg",
  },
  {
    word: "igual",
    translation: "same/equal",
    category: "adjective",
    example: "Todos los carriles tienen la misma velocidad máxima.",
  },
  {
    word: "distinto",
    translation: "different/distinct",
    category: "adjective",
    example: "Cada señal tiene un significado distinto.",
  },
  {
    word: "previo",
    translation: "previous/prior",
    category: "adjective",
    example: "Es necesario un examen previo para obtener el permiso.",
  },
  {
    word: "posterior",
    translation: "subsequent/rear",
    category: "adjective",
    example: "La revisión posterior es obligatoria.",
  },
  {
    word: "mínimo",
    translation: "minimum",
    category: "adjective",
    example: "Se requiere un nivel mínimo de atención.",
  },
  {
    word: "máximo",
    translation: "maximum",
    category: "adjective",
    example: "El peso máximo autorizado es de 3500kg.",
  },
  {
    word: "nuevo",
    translation: "new",
    category: "adjective",
    example: "Este es un nuevo tipo de señal.",
  },
  {
    word: "viejo",
    translation: "old",
    category: "adjective",
    example: "Un coche viejo puede ser menos seguro.",
  },
  {
    word: "obvio",
    translation: "obvious",
    category: "adjective",
    example: "Es obvio que no se puede aparcar aquí.",
  },
  {
    word: "innecesario",
    translation: "unnecessary",
    category: "adjective",
    example: "Evita realizar maniobras innecesarias.",
  },
  {
    word: "correcto",
    translation: "correct/right",
    category: "adjective",
    example: "Siga el carril correcto.",
  },
  {
    word: "incorrecto",
    translation: "incorrect/wrong",
    category: "adjective",
    example: "Tomar una salida incorrecta puede ser peligroso.",
  },
  {
    word: "válido",
    translation: "valid",
    category: "adjective",
    example: "El permiso de conducir debe estar válido.",
  },
  {
    word: "inválido",
    translation: "invalid",
    category: "adjective",
    example: "Un documento inválido no será aceptado.",
  },
  {
    word: "necesario",
    translation: "necessary",
    category: "adjective",
    example: "Es necesario llevar la documentación del vehículo.",
  },
  {
    word: "inseguro",
    translation: "unsafe/insecure",
    category: "adjective",
    example: "Conducir con neumáticos gastados es inseguro.",
  },
  {
    word: "estable",
    translation: "stable",
    category: "adjective",
    example: "Mantenga una velocidad estable.",
  },
  {
    word: "inestable",
    translation: "unstable",
    category: "adjective",
    example: "Una carga mal sujeta puede volver el vehículo inestable.",
  },
  {
    word: "limpio",
    translation: "clean",
    category: "adjective",
    example: "Mantenga los cristales limpios para una buena visibilidad.",
  },
  {
    word: "sucio",
    translation: "dirty",
    category: "adjective",
    example: "Un vehículo sucio puede ocultar la matrícula.",
  },
  {
    word: "ordenado",
    translation: "orderly/tidy",
    category: "adjective",
    example: "El tráfico debe ser ordenado.",
  },
  {
    word: "desordenado",
    translation: "disorderly/messy",
    category: "adjective",
    example: "Evite el comportamiento desordenado en la vía.",
  },
  {
    word: "cómodo",
    translation: "comfortable",
    category: "adjective",
    example: "Ajuste el asiento para una postura cómoda.",
  },
  {
    word: "incómodo",
    translation: "uncomfortable",
    category: "adjective",
    example: "Una conducción incómoda puede distraer.",
  },
  {
    word: "directo",
    translation: "direct",
    category: "adjective",
    example: "Tome la ruta más directa si es segura.",
  },
  {
    word: "indirecto",
    translation: "indirect",
    category: "adjective",
    example: "La luz indirecta puede afectar la visibilidad.",
  },
  {
    word: "habitual",
    translation: "usual/habitual",
    category: "adjective",
    example: "Siga su carril habitual a menos que se indique lo contrario.",
  },
  {
    word: "rutinario",
    translation: "routine",
    category: "adjective",
    example: "Un control rutinario de alcoholemia.",
  },
  {
    word: "temporal",
    translation: "temporary",
    category: "adjective",
    example: "Hay una señalización temporal por obras.",
  },
  {
    word: "permanente",
    translation: "permanent",
    category: "adjective",
    example: "Esta es una señal permanente.",
  },
  {
    word: "obligado",
    translation: "obliged/forced",
    category: "adjective",
    example: "Estás obligado a detenerte ante un stop.",
  },
  {
    word: "permitido",
    translation: "allowed/permitted",
    category: "adjective",
    example: "El adelantamiento está permitido en esta sección.",
  },
  {
    word: "prioritario",
    translation: "priority",
    category: "adjective",
    example: "El vehículo de emergencia tiene paso prioritario.",
  },
  {
    word: "secundario",
    translation: "secondary",
    category: "adjective",
    example: "Acceda desde una vía secundaria con precaución.",
  },
  {
    word: "adicional",
    translation: "additional",
    category: "adjective",
    example: "Puede haber información adicional en el panel.",
  },
  {
    word: "principal",
    translation: "main/principal",
    category: "adjective",
    example: "La carretera principal tiene preferencia.",
  },
  {
    word: "inteligente",
    translation: "smart/intelligent",
    category: "adjective",
    example: "Un sistema de tráfico inteligente puede reducir atascos.",
  },
  {
    word: "torpe",
    translation: "clumsy/awkward",
    category: "adjective",
    example: "Una maniobra torpe puede causar un accidente.",
  },
  {
    word: "eficaz",
    translation: "effective/efficient",
    category: "adjective",
    example: "Una frenada eficaz es crucial.",
  },
  {
    word: "ineficaz",
    translation: "ineffective/inefficient",
    category: "adjective",
    example: "Una señalización ineficaz puede confundir.",
  },
  {
    word: "señalización",
    translation: "signage",
    category: "noun",
    example: "La señalización vertical indica la velocidad máxima.",
  },
  {
    word: "estacionamiento",
    translation: "parking",
    category: "noun",
    example: "El estacionamiento está prohibido en esta zona.",
  },
  {
    word: "remolque",
    translation: "trailer",
    category: "noun",
    example: "El vehículo tractor arrastra un remolque ligero.",
  },
  {
    word: "ciclista",
    translation: "cyclist",
    category: "noun",
    example: "El ciclista debe respetar las normas de circulación.",
  },
  {
    word: "neumático",
    translation: "tire",
    category: "noun",
    example: "Es importante revisar la presión del neumático.",
  },
  {
    word: "estacionar",
    translation: "to park",
    category: "verb",
    example: "No se puede estacionar en doble fila.",
  },
  {
    word: "inmovilizar",
    translation: "to immobilize",
    category: "verb",
    example: "El agente puede inmovilizar el vehículo si carece de seguro.",
  },
  {
    word: "remolcar",
    translation: "to tow",
    category: "verb",
    example: "La grúa va a remolcar el coche averiado.",
  },
  {
    word: "infringir",
    translation: "to infringe/violate",
    category: "verb",
    example: "Infringir las normas de tráfico conlleva una sanción.",
  },
  {
    word: "cumplir",
    translation: "to comply with",
    category: "verb",
    example: "Es obligatorio cumplir con las indicaciones del agente.",
  },
  {
    word: "reglamentario",
    translation: "regulatory/statutory",
    category: "adjective",
    example: "El uso del casco es reglamentario para motoristas.",
  },
  {
    word: "reflectante",
    translation: "reflective",
    category: "adjective",
    example: "Es obligatorio llevar un chaleco reflectante en caso de avería.",
  },
  {
    word: "luminoso",
    translation: "luminous/bright",
    category: "adjective",
    example: "Las señales luminosas tienen prioridad sobre las verticales.",
  },
  {
    word: "técnico",
    translation: "technical",
    category: "adjective",
    example: "La inspección técnica del vehículo es periódica.",
  },
  {
    word: "preventivo",
    translation: "preventive",
    category: "adjective",
    example: "Se realizan controles de alcoholemia preventivos.",
  },
  {
    word: "autopista",
    translation: "highway/motorway",
    category: "noun",
    example: "La velocidad máxima en autopista es 120 km/h.",
  },
  {
    word: "ciclomotor",
    translation: "moped",
    category: "noun",
    example: "El ciclomotor no puede circular por autopistas.",
  },
  {
    word: "autobús",
    translation: "bus",
    category: "noun",
    example: "El autobús tiene prioridad en las paradas.",
  },
  {
    word: "semáforo",
    translation: "traffic light",
    category: "noun",
    example: "Respeta las indicaciones del semáforo.",
  },
  {
    word: "marca",
    translation: "marking/sign",
    category: "noun",
    example: "Las marcas viales delimitan los carriles.",
  },
  {
    word: "dispositivo",
    translation: "device",
    category: "noun",
    example: "Los dispositivos de seguridad son obligatorios.",
  },
  {
    word: "emergencia",
    translation: "emergency",
    category: "noun",
    example: "Usa las luces de emergencia si es necesario.",
  },
  {
    word: "avería",
    translation: "breakdown",
    category: "noun",
    example: "En caso de avería, para en lugar seguro.",
  },
  {
    word: "grúa",
    translation: "tow truck",
    category: "noun",
    example: "La grúa retirará el vehículo mal aparcado.",
  },
  {
    word: "seguro",
    translation: "insurance",
    category: "noun",
    example: "Es obligatorio tener seguro del vehículo.",
  },
  {
    word: "alcoholemia",
    translation: "blood alcohol test",
    category: "noun",
    example: "El control de alcoholemia es aleatorio.",
  },
  {
    word: "inspector",
    translation: "inspector",
    category: "noun",
    example: "El inspector revisa la documentación.",
  },
  {
    word: "tráfico",
    translation: "traffic",
    category: "noun",
    example: "El tráfico está muy denso esta mañana.",
  },
  {
    word: "circulación",
    translation: "traffic/circulation",
    category: "noun",
    example: "La circulación está cortada por obras.",
  },
  {
    word: "parada",
    translation: "stop/bus stop",
    category: "noun",
    example: "No aparques cerca de una parada de autobús.",
  },
  {
    word: "zona",
    translation: "zone/area",
    category: "noun",
    example: "Esta es una zona de velocidad limitada.",
  },
  {
    word: "límite",
    translation: "limit",
    category: "noun",
    example: "Respeta el límite de velocidad establecido.",
  },
  {
    word: "control",
    translation: "control/checkpoint",
    category: "noun",
    example: "Hay un control de documentación más adelante.",
  },
  {
    word: "revisión",
    translation: "inspection/review",
    category: "noun",
    example: "La revisión del vehículo es anual.",
  },
  {
    word: "reglamento",
    translation: "regulation",
    category: "noun",
    example: "El reglamento de circulación es de obligado cumplimiento.",
  },
  {
    word: "norma",
    translation: "rule/standard",
    category: "noun",
    example: "Las normas de tráfico protegen a todos.",
  },
  {
    word: "código",
    translation: "code",
    category: "noun",
    example: "El código de circulación regula el tráfico.",
  },
  {
    word: "artículo",
    translation: "article",
    category: "noun",
    example: "El artículo 47 regula los adelantamientos.",
  },
  {
    word: "disposición",
    translation: "provision/regulation",
    category: "noun",
    example: "Esta disposición está vigente desde 2003.",
  },
  {
    word: "decreto",
    translation: "decree",
    category: "noun",
    example: "El Real Decreto establece las normas básicas.",
  },
  {
    word: "boletín",
    translation: "bulletin",
    category: "noun",
    example: "Las normas se publican en el Boletín Oficial.",
  },
  {
    word: "estado",
    translation: "state/condition",
    category: "noun",
    example: "El estado de la carretera influye en la conducción.",
  },
  {
    word: "ministerio",
    translation: "ministry",
    category: "noun",
    example: "El Ministerio de Interior regula el tráfico.",
  },
  {
    word: "competencia",
    translation: "competence/jurisdiction",
    category: "noun",
    example: "Esta infracción es competencia municipal.",
  },
  {
    word: "régimen",
    translation: "regime/system",
    category: "noun",
    example: "El régimen sancionador es muy estricto.",
  },
  {
    word: "procedimiento",
    translation: "procedure",
    category: "noun",
    example: "Sigue el procedimiento establecido para recurrir.",
  },
  {
    word: "expedir",
    translation: "to issue",
    category: "verb",
    example: "La DGT expide los permisos de conducir.",
  },
  {
    word: "autorizar",
    translation: "to authorize",
    category: "verb",
    example: "Solo pueden autorizar el paso los agentes.",
  },
  {
    word: "establecer",
    translation: "to establish",
    category: "verb",
    example: "Las ordenanzas establecen las normas locales.",
  },
  {
    word: "regular",
    translation: "to regulate",
    category: "verb",
    example: "Los semáforos regulan el tráfico urbano.",
  },
  {
    word: "determinar",
    translation: "to determine",
    category: "verb",
    example: "El juez determinará la sanción correspondiente.",
  },
  {
    word: "aplicar",
    translation: "to apply",
    category: "verb",
    example: "Se aplica una multa por exceso de velocidad.",
  },
  {
    word: "constituir",
    translation: "to constitute",
    category: "verb",
    example: "Esta acción constituye una infracción grave.",
  },
  {
    word: "exceptuar",
    translation: "to except",
    category: "verb",
    example: "Se exceptúan los vehículos de emergencia.",
  },
  {
    word: "suspender",
    translation: "to suspend",
    category: "verb",
    example: "Pueden suspender el permiso de conducir.",
  },
  {
    word: "retirar",
    translation: "to withdraw/remove",
    category: "verb",
    example: "Van a retirar el vehículo mal aparcado.",
  },
  {
    word: "sustituir",
    translation: "to replace/substitute",
    category: "verb",
    example: "Sustituye las luces fundidas inmediatamente.",
  },
  {
    word: "adaptar",
    translation: "to adapt",
    category: "verb",
    example: "Adapta la velocidad a las condiciones.",
  },
  {
    word: "modificar",
    translation: "to modify",
    category: "verb",
    example: "No modifiques el vehículo sin autorización.",
  },
  {
    word: "homologar",
    translation: "to approve/certify",
    category: "verb",
    example: "Todos los cascos deben estar homologados.",
  },
  {
    word: "matricular",
    translation: "to register",
    category: "verb",
    example: "Hay que matricular el vehículo en España.",
  },
  {
    word: "inspeccionar",
    translation: "to inspect",
    category: "verb",
    example: "Inspecciona el vehículo antes de viajar.",
  },
  {
    word: "verificar",
    translation: "to verify",
    category: "verb",
    example: "Verifica que la documentación esté en regla.",
  },
  {
    word: "acreditar",
    translation: "to accredit/prove",
    category: "verb",
    example: "Acredita tu identidad con el DNI.",
  },
  {
    word: "demostrar",
    translation: "to demonstrate",
    category: "verb",
    example: "Demuestra que conoces las normas.",
  },
  {
    word: "justificar",
    translation: "to justify",
    category: "verb",
    example: "Justifica el motivo de tu maniobra.",
  },
  {
    word: "imponer",
    translation: "to impose",
    category: "verb",
    example: "Le van a imponer una multa por aparcar mal.",
  },
  {
    word: "tramitar",
    translation: "to process",
    category: "verb",
    example: "Tramita la denuncia en la comisaría.",
  },
  {
    word: "recurrir",
    translation: "to appeal",
    category: "verb",
    example: "Puedes recurrir la multa si no estás conforme.",
  },
  {
    word: "notificar",
    translation: "to notify",
    category: "verb",
    example: "Te notificarán la sanción por correo.",
  },
  {
    word: "comunicar",
    translation: "to communicate",
    category: "verb",
    example: "Comunica cualquier cambio de domicilio.",
  },
  {
    word: "informar",
    translation: "to inform",
    category: "verb",
    example: "Informa sobre los accidentes a las autoridades.",
  },
  {
    word: "señalizar",
    translation: "to signpost",
    category: "verb",
    example: "Van a señalizar mejor esta intersección.",
  },
  {
    word: "balizar",
    translation: "to mark with beacons",
    category: "verb",
    example: "Balizan la zona de obras con conos.",
  },
  {
    word: "oficial",
    translation: "official",
    category: "adjective",
    example: "Consulta solo fuentes oficiales.",
  },
  {
    word: "competente",
    translation: "competent",
    category: "adjective",
    example: "Acude a la autoridad competente.",
  },
  {
    word: "vigente",
    translation: "current/in force",
    category: "adjective",
    example: "La normativa vigente es de 2003.",
  },
  {
    word: "aplicable",
    translation: "applicable",
    category: "adjective",
    example: "Esta norma es aplicable a todos los vehículos.",
  },
  {
    word: "específico",
    translation: "specific",
    category: "adjective",
    example: "Hay normas específicas para motocicletas.",
  },
  {
    word: "general",
    translation: "general",
    category: "adjective",
    example: "Esta es la norma general de circulación.",
  },
  {
    word: "excepcional",
    translation: "exceptional",
    category: "adjective",
    example: "Solo en casos excepcionales se permite.",
  },
  {
    word: "ordinario",
    translation: "ordinary",
    category: "adjective",
    example: "En condiciones ordinarias de tráfico.",
  },
  {
    word: "extraordinario",
    translation: "extraordinary",
    category: "adjective",
    example: "Medidas extraordinarias por la nevada.",
  },
  {
    word: "provisional",
    translation: "provisional/temporary",
    category: "adjective",
    example: "Permiso provisional hasta recibir el definitivo.",
  },
  {
    word: "definitivo",
    translation: "definitive/final",
    category: "adjective",
    example: "La resolución definitiva tardará dos meses.",
  },
  {
    word: "inmediato",
    translation: "immediate",
    category: "adjective",
    example: "Aplicación inmediata de la nueva norma.",
  },
  {
    word: "posterior",
    translation: "subsequent/later",
    category: "adjective",
    example: "La inspección posterior confirmó los daños.",
  },
  {
    word: "simultáneo",
    translation: "simultaneous",
    category: "adjective",
    example: "Control simultáneo de velocidad y documentación.",
  },
  {
    word: "sucesivo",
    translation: "successive",
    category: "adjective",
    example: "En controles sucesivos se detectaron más infracciones.",
  },
  {
    word: "continuo",
    translation: "continuous",
    category: "adjective",
    example: "Línea continua, prohibido adelantar.",
  },
  {
    word: "discontinuo",
    translation: "discontinuous",
    category: "adjective",
    example: "Línea discontinua, adelantamiento permitido.",
  },
  {
    word: "homologado",
    translation: "approved/certified",
    category: "adjective",
    example: "Solo cascos homologados son válidos.",
  },
  {
    word: "reglamentario",
    translation: "regulatory",
    category: "adjective",
    example: "Equipo reglamentario obligatorio en el vehículo.",
  },
  {
    word: "preseñalización",
    translation: "pre-signaling",
    category: "noun",
    example: "La preseñalización indica la próxima salida.",
  },
  {
    word: "enlace",
    translation: "junction/link",
    category: "noun",
    example: "El enlace conecta dos autopistas.",
  },
  {
    word: "ramal",
    translation: "branch/ramp",
    category: "noun",
    example: "Toma el ramal hacia la ciudad.",
  },
  {
    word: "itinerario",
    translation: "itinerary/route",
    category: "noun",
    example: "Sigue el itinerario señalizado.",
  },
  {
    word: "transporte especial",
    translation: "special transport",
    category: "noun",
    example: "El transporte especial necesita autorización.",
  },
  {
    word: "vehículo piloto",
    translation: "pilot vehicle",
    category: "noun",
    example: "El vehículo piloto acompaña cargas especiales.",
  },
  {
    word: "convoy",
    translation: "convoy",
    category: "noun",
    example: "El convoy militar tiene prioridad de paso.",
  },
  {
    word: "balizamiento",
    translation: "beaconing/marking",
    category: "noun",
    example: "El balizamiento delimita las obras.",
  },
  {
    word: "cebreado",
    translation: "chevron markings",
    category: "noun",
    example: "El cebreado prohíbe la circulación.",
  },
  {
    word: "señalización circunstancial",
    translation: "circumstantial signaling",
    category: "noun",
    example: "La señalización circunstancial es temporal.",
  },
  {
    word: "telepeaje",
    translation: "electronic toll",
    category: "noun",
    example: "El telepeaje acelera el paso por autopistas.",
  },
  {
    word: "carril reservado",
    translation: "reserved lane",
    category: "noun",
    example: "El carril reservado es para autobuses.",
  },
  {
    word: "VAO",
    translation: "high occupancy vehicle",
    category: "noun",
    example: "Los VAO pueden usar este carril.",
  },
  {
    word: "rotativo",
    translation: "rotating beacon",
    category: "noun",
    example: "El rotativo naranja señala vehículos especiales.",
  },
  {
    word: "panel de mensaje variable",
    translation: "variable message panel",
    category: "noun",
    example: "El panel de mensaje variable informa del tráfico.",
  },
  {
    word: "dispositivo de barrera",
    translation: "barrier device",
    category: "noun",
    example: "El dispositivo de barrera cierra el paso.",
  },
  {
    word: "apartadero",
    translation: "lay-by/pullout",
    category: "noun",
    example: "Para en el apartadero si es necesario.",
  },
  {
    word: "vía de servicio",
    translation: "service road",
    category: "noun",
    example: "La vía de servicio da acceso a los servicios.",
  },
  {
    word: "área de servicio",
    translation: "service area",
    category: "noun",
    example: "Para en el área de servicio a repostar.",
  },
  {
    word: "senda ciclable",
    translation: "cycle path",
    category: "noun",
    example: "La senda ciclable es solo para bicicletas.",
  },
  {
    word: "paso a nivel",
    translation: "level crossing",
    category: "noun",
    example: "Extrema la precaución en el paso a nivel.",
  },
  {
    word: "puente móvil",
    translation: "movable bridge",
    category: "noun",
    example: "Espera la señal en el puente móvil.",
  },
  {
    word: "pontón trasbordador",
    translation: "ferry bridge",
    category: "noun",
    example: "El pontón trasbordador transporta vehículos.",
  },
  {
    word: "isleta",
    translation: "traffic island",
    category: "noun",
    example: "La isleta canaliza el tráfico.",
  },
  {
    word: "mediana",
    translation: "central reservation",
    category: "noun",
    example: "No pares en la mediana.",
  },
  {
    word: "separador",
    translation: "divider",
    category: "noun",
    example: "El separador divide los sentidos de circulación.",
  },
  {
    word: "vado",
    translation: "driveway access",
    category: "noun",
    example: "No obstruyas el vado señalizado.",
  },
  {
    word: "carga y descarga",
    translation: "loading and unloading",
    category: "noun",
    example: "Esta zona es de carga y descarga.",
  },
  {
    word: "paso de peatones",
    translation: "pedestrian crossing",
    category: "noun",
    example: "Cede el paso en el paso de peatones.",
  },
  {
    word: "línea de detención",
    translation: "stop line",
    category: "noun",
    example: "Detente antes de la línea de detención.",
  },
  {
    word: "línea longitudinal",
    translation: "longitudinal line",
    category: "noun",
    example: "La línea longitudinal delimita carriles.",
  },
  {
    word: "marca vial",
    translation: "road marking",
    category: "noun",
    example: "Las marcas viales guían la circulación.",
  },
  {
    word: "paso rebajado",
    translation: "lowered crossing",
    category: "noun",
    example: "El paso rebajado facilita el acceso.",
  },
  {
    word: "extinción de incendios",
    translation: "fire fighting",
    category: "noun",
    example: "Vehículo de extinción de incendios.",
  },
  {
    word: "protección civil",
    translation: "civil protection",
    category: "noun",
    example: "Los servicios de protección civil.",
  },
  {
    word: "asistencia sanitaria",
    translation: "medical assistance",
    category: "noun",
    example: "Ambulancia de asistencia sanitaria.",
  },
  {
    word: "servicio urgente",
    translation: "emergency service",
    category: "noun",
    example: "Vehículo en servicio urgente.",
  },
  {
    word: "señal acústica",
    translation: "acoustic signal",
    category: "noun",
    example: "La señal acústica es obligatoria.",
  },
  {
    word: "señal luminosa",
    translation: "light signal",
    category: "noun",
    example: "La señal luminosa es prioritaria.",
  },
  {
    word: "carretera convencional",
    translation: "conventional road",
    category: "noun",
    example: "En carretera convencional el límite es 90 km/h.",
  },
  {
    word: "masa máxima autorizada",
    translation: "maximum authorized weight",
    category: "noun",
    example: "Respeta la masa máxima autorizada.",
  },
  {
    word: "dimensiones máximas",
    translation: "maximum dimensions",
    category: "noun",
    example: "Las dimensiones máximas están reguladas.",
  },
  {
    word: "mercancías peligrosas",
    translation: "dangerous goods",
    category: "noun",
    example: "Transporte especial de mercancías peligrosas.",
  },
  {
    word: "conductor novel",
    translation: "novice driver",
    category: "noun",
    example: "El conductor novel debe señalizarse.",
  },
  {
    word: "aprendizaje de conducción",
    translation: "driving learning",
    category: "noun",
    example: "Vehículo en aprendizaje de conducción.",
  },
  {
    word: "inspección técnica",
    translation: "technical inspection",
    category: "noun",
    example: "La inspección técnica es obligatoria.",
  },
  {
    word: "distintivo de nacionalidad",
    translation: "nationality badge",
    category: "noun",
    example: "El distintivo de nacionalidad es obligatorio.",
  },
  {
    word: "servicio público",
    translation: "public service",
    category: "noun",
    example: "Vehículo destinado al servicio público.",
  },
  {
    word: "placa de ensayo",
    translation: "test plate",
    category: "noun",
    example: "La placa de ensayo es para vehículos experimentales.",
  },
  {
    word: "minusválido",
    translation: "disabled person",
    category: "noun",
    example: "Plaza reservada para minusválido.",
  },
  {
    word: "dispositivo de preseñalización",
    translation: "warning device",
    category: "noun",
    example: "Coloca el dispositivo de preseñalización.",
  },
  {
    word: "taxímetro",
    translation: "taximeter",
    category: "noun",
    example: "El taxímetro calcula el coste del viaje.",
  },
  {
    word: "cargas que sobresalen",
    translation: "protruding loads",
    category: "noun",
    example: "Señaliza las cargas que sobresalen.",
  },
  {
    word: "fluidez del tráfico",
    translation: "traffic flow",
    category: "noun",
    example: "Las obras afectan la fluidez del tráfico.",
  },
  {
    word: "restricciones de circulación",
    translation: "traffic restrictions",
    category: "noun",
    example: "Hay restricciones de circulación por obras.",
  },
  {
    word: "regulación del tráfico",
    translation: "traffic regulation",
    category: "noun",
    example: "La regulación del tráfico es municipal.",
  },
  {
    word: "vigilancia del tráfico",
    translation: "traffic surveillance",
    category: "noun",
    example: "La vigilancia del tráfico es constante.",
  },
  {
    word: "control del tráfico",
    translation: "traffic control",
    category: "noun",
    example: "El control del tráfico es automático.",
  },
  {
    word: "gestión del tráfico",
    translation: "traffic management",
    category: "noun",
    example: "La gestión del tráfico es telemática.",
  },
  {
    word: "saturación del tráfico",
    translation: "traffic saturation",
    category: "noun",
    example: "La saturación del tráfico causa retrasos.",
  },
  {
    word: "densidad del tráfico",
    translation: "traffic density",
    category: "noun",
    example: "La densidad del tráfico es alta.",
  },
  {
    word: "congestión",
    translation: "congestion",
    category: "noun",
    example: "La congestión obliga a usar rutas alternativas.",
  },
  {
    word: "retención",
    translation: "traffic jam",
    category: "noun",
    example: "Hay retención de 5 kilómetros.",
  },
  {
    word: "atasco",
    translation: "traffic jam",
    category: "noun",
    example: "El atasco dura dos horas.",
  },
  {
    word: "inmediatamente",
    translation: "immediately",
    category: "adverb",
    example: "Detente inmediatamente ante la señal de stop.",
  },
  {
    word: "siempre",
    translation: "always",
    category: "adverb",
    example: "Siempre debes respetar las señales de tráfico.",
  },
  {
    word: "únicamente",
    translation: "only/solely",
    category: "adverb",
    example: "Únicamente los vehículos autorizados pueden usar este carril.",
  },
  {
    word: "especialmente",
    translation: "especially",
    category: "adverb",
    example: "Conduce con precaución, especialmente en condiciones de lluvia.",
  },
  {
    word: "normalmente",
    translation: "normally",
    category: "adverb",
    example: "Normalmente debe circular por el carril derecho.",
  },
  {
    word: "previamente",
    translation: "previously/beforehand",
    category: "adverb",
    example:
      "El conductor debe advertir previamente su maniobra con las señales reglamentarias.",
  },
  {
    word: "correctamente",
    translation: "correctly",
    category: "adverb",
    example: "Es necesario colocar correctamente el cinturón de seguridad.",
  },
  {
    word: "solamente",
    translation: "only",
    category: "adverb",
    example:
      "Solamente los vehículos de emergencia pueden exceder el límite de velocidad.",
  },
  {
    word: "obligatoriamente",
    translation: "mandatorily",
    category: "adverb",
    example: "Debes usar obligatoriamente el casco en la motocicleta.",
  },
  {
    word: "rápidamente",
    translation: "quickly/rapidly",
    category: "adverb",
    example: "Abandona rápidamente el vehículo en caso de incendio.",
  },
  {
    word: "generalmente",
    translation: "generally",
    category: "adverb",
    example:
      "Generalmente, los límites de velocidad son menores en zonas urbanas.",
  },
  {
    word: "debidamente",
    translation: "properly/duly",
    category: "adverb",
    example: "Toda carga debe estar debidamente asegurada.",
  },
  {
    word: "completamente",
    translation: "completely",
    category: "adverb",
    example: "Detén completamente el vehículo en los pasos a nivel.",
  },
  {
    word: "excepcionalmente",
    translation: "exceptionally",
    category: "adverb",
    example:
      "Excepcionalmente, se permite circular por el arcén en caso de emergencia.",
  },
  {
    word: "actualmente",
    translation: "currently",
    category: "adverb",
    example: "Actualmente, el límite de velocidad en esta vía es de 50 km/h.",
  },
  {
    word: "posteriormente",
    translation: "later/afterwards",
    category: "adverb",
    example:
      "Si no llevas la documentación, deberás presentarla posteriormente en la comisaría.",
  },
  {
    word: "suficientemente",
    translation: "sufficiently",
    category: "adverb",
    example:
      "Mantén una distancia suficientemente segura con el vehículo de delante.",
  },
  {
    word: "prácticamente",
    translation: "practically/virtually",
    category: "adverb",
    example: "Con niebla densa, la visibilidad es prácticamente nula.",
  },
  {
    word: "automáticamente",
    translation: "automatically",
    category: "adverb",
    example:
      "El sistema de frenado se activa automáticamente en caso de peligro.",
  },
  {
    word: "nunca",
    translation: "never",
    category: "adverb",
    example: "Nunca cruces cuando el semáforo está en rojo.",
  },
  // Additional nouns found in the traffic regulations
  {
    word: "pavimento",
    translation: "pavement",
    category: "noun",
    example: "El pavimento estaba mojado y resbaladizo.",
  },
  {
    word: "deslumbramiento",
    translation: "glare/dazzling",
    category: "noun",
    example: "Reduce la velocidad en caso de deslumbramiento.",
  },
  {
    word: "caballería",
    translation: "cavalry/horse",
    category: "noun",
    example: "Las caballerías tienen que circular por el arcén.",
  },
  {
    word: "visibilidad",
    translation: "visibility",
    category: "noun",
    example: "La visibilidad era reducida debido a la niebla.",
  },
  {
    word: "apartadero",
    translation: "lay-by/pullout",
    category: "noun",
    example: "Utilizó el apartadero para detenerse.",
  },
  {
    word: "inmovilización",
    translation: "immobilization",
    category: "noun",
    example: "La inmovilización del vehículo es obligatoria en ese caso.",
  },
  {
    word: "autorización complementaria",
    translation: "supplementary authorization",
    category: "noun",
    example: "Necesitas una autorización complementaria para ese transporte.",
  },

  // Additional verbs found in the traffic regulations
  {
    word: "cerciorarse",
    translation: "to make sure",
    category: "verb",
    example: "Debes cerciorarse de que no hay peligro antes de adelantar.",
  },
  {
    word: "vulnerar",
    translation: "to violate/breach",
    category: "verb",
    example: "No vulneres la prioridad de paso en las intersecciones.",
  },
  {
    word: "acondicionarse",
    translation: "to condition oneself/to adapt",
    category: "verb",
    example: "El conductor debe acondicionarse a las circunstancias del tráfico.",
  },
  {
    word: "detenerse",
    translation: "to stop",
    category: "verb",
    example: "Ante un stop debes detenerse completamente.",
  },
  {
    word: "reanudar",
    translation: "to resume",
    category: "verb",
    example: "Reanuda la marcha cuando sea seguro.",
  },
  {
    word: "estacionar",
    translation: "to park",
    category: "verb",
    example: "No estaciones en lugares prohibidos.",
  },

  // Additional adjectives found in the traffic regulations
  {
    word: "diáfano",
    translation: "transparent/clear",
    category: "adjective",
    example: "La superficie acristalada debe permitir la visibilidad diáfana.",
  },
  {
    word: "preceptivo",
    translation: "mandatory/required",
    category: "adjective",
    example: "Es preceptivo llevar el dispositivo de retención infantil.",
  },
  {
    word: "inexcusable",
    translation: "inexcusable/mandatory",
    category: "adjective",
    example: "Es inexcusable cumplir las normas de tráfico.",
  },
  {
    word: "inmediato",
    translation: "immediate",
    category: "adjective",
    example: "Debes detenerte de inmediato cuando te lo indique un agente.",
  },
  {
    word: "exento",
    translation: "exempt",
    category: "adjective",
    example: "Los vehículos de emergencia están exentos de algunas normas.",
  },
  {
    word: "paulatino",
    translation: "gradual",
    category: "adjective",
    example: "La reducción paulatina de la velocidad es más segura.",
  },

  // Additional adverbs found in the traffic regulations
  {
    word: "racionalmente",
    translation: "rationally",
    category: "adverb",
    example: "Se debe prever racionalmente la irrupción de peatones.",
  },
  {
    word: "expresamente",
    translation: "expressly",
    category: "adverb",
    example: "Lo que está expresamente prohibido por las normas.",
  },
  {
    word: "manifiestamente",
    translation: "manifestly/clearly",
    category: "adverb",
    example: "Personas manifiestamente impedidas requieren especial atención.",
  },
  {
    word: "principalmente",
    translation: "mainly/principally",
    category: "adverb",
    example: "Debes ser cauteloso principalmente en zonas escolares.",
  },
  {
    word: "convenientemente",
    translation: "conveniently/properly",
    category: "adverb",
    example: "La carga debe estar convenientemente asegurada.",
  },
  {
    word: "eficazmente",
    translation: "effectively",
    category: "adverb",
    example: "Debes señalizar eficazmente cualquier obstáculo en la vía.",
  },
  {
    word: "prácticamente",
    translation: "practically",
    category: "adverb",
    example: "Con niebla densa, la visibilidad es prácticamente nula.",
  },
];
