// Spanish DGT Driving Vocabulary Data
// This file contains all the vocabulary terms for the DGT flashcard application

window.vocabularyData = [
  {
    word: "accidente",
    translation: "accident",
    perevod: "авария",
    category: "noun",
    example: "Evita los accidentes conduciendo con prudencia",
  },
  {
    word: "acondicionarse",
    translation: "to condition oneself/to adapt",
    perevod: "адаптироваться или приспосабливаться",
    category: "verb",
    example:
      "El conductor debe acondicionarse a las circunstancias del tráfico.",
  },
  {
    word: "acreditar",
    translation: "to accredit",
    perevod: "аккредитовать",
    category: "verb",
    example: "Acredita tu identidad con el DNI.",
  },
  {
    word: "actualmente",
    translation: "currently",
    perevod: "в настоящее время",
    category: "adverb",
    example: "Actualmente, el límite de velocidad en esta vía es de 50 km/h.",
  },
  {
    word: "adaptar",
    translation: "to adapt",
    perevod: "адаптироваться",
    category: "verb",
    example: "Adapta la velocidad a las condiciones.",
  },
  {
    word: "adecuado",
    translation: "adequate/appropriate",
    perevod: "адекватный или уместный",
    category: "adjective",
    example: "Mantén una velocidad adecuada",
  },
  {
    word: "adelantar",
    translation: "to overtake",
    perevod: "чтобы обогнать",
    category: "verb",
    example: "Solo adelanta cuando sea seguro",
  },
  {
    word: "adicional",
    translation: "additional",
    perevod: "дополнительный",
    category: "adjective",
    example: "Puede haber información adicional en el panel.",
  },
  {
    word: "advertir",
    translation: "to warn",
    perevod: "чтобы предупредить",
    category: "verb",
    example: "Advierte del peligro con las luces",
  },
  {
    word: "agente",
    translation: "officer/agent",
    perevod: "офицер или агент",
    category: "noun",
    example: "El agente de tráfico dirige la circulación",
  },
  {
    word: "alcoholemia",
    translation: "blood alcohol test",
    perevod: "анализ алкоголя в крови",
    category: "noun",
    example: "El control de alcoholemia es aleatorio.",
  },
  {
    word: "alumbrado",
    translation: "lighting",
    perevod: "освещение",
    category: "noun",
    example: "El alumbrado público facilita la visión",
  },
  {
    word: "ancho",
    translation: "wide",
    perevod: "широкий",
    category: "adjective",
    example: "Carril ancho para adelantar",
  },
  {
    word: "anterior",
    translation: "previous/front",
    perevod: "предыдущий/передний",
    category: "adjective",
    example: "El vehículo anterior frena",
  },
  {
    word: "apagado",
    translation: "off/turned off",
    perevod: "выключить или выключить",
    category: "verb",
    example: "Motor apagado en semáforos largos",
  },
  {
    word: "apartadero",
    translation: "lay-by/pullout",
    perevod: "проложить или вытянуть",
    category: "noun",
    example: "Para en el apartadero si es necesario.",
  },
  {
    word: "apartadero",
    translation: "lay-by/pullout",
    perevod: "проложить или вытянуть",
    category: "verb",
    example: "Utilizó el apartadero para detenerse.",
  },
  {
    word: "aplicable",
    translation: "applicable",
    perevod: "применимый",
    category: "adjective",
    example: "Esta norma es aplicable a todos los vehículos.",
  },
  {
    word: "aplicar",
    translation: "to apply",
    perevod: "подать заявку",
    category: "verb",
    example: "Se aplica una multa por exceso de velocidad.",
  },
  {
    word: "aprendizaje de conducción",
    translation: "driving learning",
    perevod: "вождение обучения",
    category: "noun",
    example: "Vehículo en aprendizaje de conducción.",
  },
  {
    word: "arcén",
    translation: "road shoulder",
    perevod: "обочина",
    category: "noun",
    example: "Para en el arcén si es necesario",
  },
  {
    word: "área de servicio",
    translation: "service area",
    perevod: "зона обслуживания",
    category: "noun",
    example: "Para en el área de servicio a repostar.",
  },
  {
    word: "artículo",
    translation: "article",
    perevod: "статья",
    category: "noun",
    example: "El artículo 47 regula los adelantamientos.",
  },
  {
    word: "asistencia sanitaria",
    translation: "medical assistance",
    perevod: "медицинская помощь",
    category: "noun",
    example: "Ambulancia de asistencia sanitaria.",
  },
  {
    word: "atasco",
    translation: "traffic jam",
    perevod: "пробка",
    category: "noun",
    example: "El atasco dura dos horas.",
  },
  {
    word: "atropellar",
    translation: "to run over",
    perevod: "переехать",
    category: "verb",
    example: "Evita atropellar a los peatones",
  },
  {
    word: "autobús",
    translation: "bus",
    perevod: "автобус",
    category: "noun",
    example: "El autobús tiene prioridad en las paradas.",
  },
  {
    word: "automáticamente",
    translation: "automatically",
    perevod: "автоматически",
    category: "adverb",
    example:
      "El sistema de frenado se activa automáticamente en caso de peligro.",
  },
  {
    word: "autopista",
    translation: "highway/motorway",
    perevod: "шоссе или автомагистраль",
    category: "noun",
    example: "La velocidad máxima en autopista es 120 km/h.",
  },
  {
    word: "autoridad",
    translation: "authority",
    perevod: "власть",
    category: "noun",
    example: "Obedece a la autoridad competente",
  },
  {
    word: "autorización complementaria",
    translation: "supplementary authorization",
    perevod: "Дополнительное разрешение",
    category: "noun",
    example: "Necesitas una autorización complementaria para ese transporte.",
  },
  {
    word: "autorizar",
    translation: "to authorize",
    perevod: "разрешить",
    category: "verb",
    example: "Solo pueden autorizar el paso los agentes.",
  },
  {
    word: "autovía",
    translation: "highway",
    perevod: "шоссе",
    category: "noun",
    example: "La velocidad máxima en autovía es 120 km/h",
  },
  {
    word: "avería",
    translation: "breakdown",
    perevod: "авария",
    category: "noun",
    example: "En caso de avería, para en lugar seguro.",
  },
  {
    word: "avisar",
    translation: "to warn/notify",
    perevod: "предупредить или уведомлять",
    category: "verb",
    example: "Avisa con las luces de emergencia",
  },
  {
    word: "bajo",
    translation: "low",
    perevod: "низкий",
    category: "adjective",
    example: "Puente bajo, altura limitada",
  },
  {
    word: "balizamiento",
    translation: "marking",
    perevod: "маркировка",
    category: "noun",
    example: "El balizamiento delimita las obras.",
  },
  {
    word: "balizar",
    translation: "to mark with markers",
    perevod: "Отметьте с помощью маркеров",
    category: "verb",
    example: "Balizan la zona de obras con conos.",
  },
  {
    word: "bloquear",
    translation: "to block",
    perevod: "чтобы заблокировать",
    category: "verb",
    example: "No bloquees las intersecciones",
  },
  {
    word: "boletín",
    translation: "bulletin",
    perevod: "Бюллетень",
    category: "noun",
    example: "Las normas se publican en el Boletín Oficial.",
  },
  {
    word: "caballería",
    translation: "cavalry/horse",
    perevod: "кавалерия или лошадь",
    category: "noun",
    example: "Las caballerías tienen que circular por el arcén.",
  },
  {
    word: "calzada",
    translation: "roadway",
    perevod: "проезжая часть",
    category: "noun",
    example: "No pares en la calzada",
  },
  {
    word: "camión",
    translation: "truck",
    perevod: "грузовик",
    category: "noun",
    example: "Los camiones tienen limitaciones especiales",
  },
  {
    word: "carga",
    translation: "load/cargo",
    perevod: "груз или груз",
    category: "noun",
    example: "La carga debe estar bien sujeta",
  },
  {
    word: "carga y descarga",
    translation: "loading and unloading",
    perevod: "загрузка и разгрузка",
    category: "noun",
    example: "Esta zona es de carga y descarga.",
  },
  {
    word: "cargar",
    translation: "to load",
    perevod: "загрузить",
    category: "verb",
    example: "Carga el vehículo correctamente",
  },
  {
    word: "cargas que sobresalen",
    translation: "protruding loads",
    perevod: "выступающие нагрузки",
    category: "noun",
    example: "Señaliza las cargas que sobresalen.",
  },
  {
    word: "carretera",
    translation: "road/highway",
    perevod: "дорога или шоссе",
    category: "noun",
    example: "La carretera está en buen estado",
  },
  {
    word: "carretera convencional",
    translation: "conventional road",
    perevod: "обычная дорога",
    category: "noun",
    example: "En carretera convencional el límite es 90 km/h.",
  },
  {
    word: "carril",
    translation: "lane",
    perevod: "полоса",
    category: "noun",
    example: "Mantente en tu carril",
  },
  {
    word: "carril reservado",
    translation: "reserved lane",
    perevod: "зарезервированная полоса",
    category: "noun",
    example: "El carril reservado es para autobuses.",
  },
  {
    word: "caso",
    translation: "case",
    perevod: "случай",
    category: "noun",
    example:
      "En caso de inmovilización de un vehículo por emergencia, ¿a qué distancia deben colocarse los dispositivos de preseñalización de peligro?",
  },
  {
    word: "cebreado",
    translation: "the zebra crossing",
    perevod: "зебра",
    category: "noun",
    example: "El cebreado prohíbe la circulación.",
  },
  {
    word: "ceder",
    translation: "to yield/give way",
    perevod: "уступить",
    category: "verb",
    example: "Cede el paso a los peatones",
  },
  {
    word: "cercano",
    translation: "near/close",
    perevod: "рядом или близко",
    category: "adjective",
    example: "Mantente cercano al carril derecho",
  },
  {
    word: "cerciorarse",
    translation: "to make sure",
    perevod: "чтобы убедиться",
    category: "verb",
    example: "Debes cerciorarse de que no hay peligro antes de adelantar.",
  },
  {
    word: "ciclista",
    translation: "cyclist",
    perevod: "велосипедист",
    category: "noun",
    example: "El ciclista debe respetar las normas de circulación.",
  },
  {
    word: "ciclomotor",
    translation: "moped",
    perevod: "мопед",
    category: "noun",
    example: "El ciclomotor no puede circular por autopistas.",
  },
  {
    word: "cinturón",
    translation: "seatbelt",
    perevod: "ремень безопасности",
    category: "noun",
    example: "Es obligatorio usar el cinturón de seguridad",
  },
  {
    word: "circulación",
    translation: "traffic/circulation",
    perevod: "трафик или циркуляция",
    category: "noun",
    example: "La circulación está cortada por obras.",
  },
  {
    word: "circular",
    translation: "to circulate/drive",
    perevod: "проезжать или водить",
    category: "verb",
    example: "Circula siempre por la derecha",
  },
  {
    word: "claro",
    translation: "clear/bright",
    perevod: "чистый или яркий",
    category: "adjective",
    example: "Conduce solo si tienes visión clara",
  },
  {
    word: "código",
    translation: "code",
    perevod: "кодекс",
    category: "noun",
    example: "El código de circulación regula el tráfico.",
  },
  {
    word: "colocar",
    translation: "to place/position",
    perevod: "поместить или положение",
    category: "verb",
    example: "Coloca el triángulo de emergencia",
  },
  {
    word: "colocarse",
    translation: "to place",
    perevod: "поместить",
    category: "verb",
    example:
      "En caso de inmovilización de un vehículo por emergencia, ¿a qué distancia deben colocarse los dispositivos de preseñalización de peligro?",
  },
  {
    word: "como",
    translation: "like",
    perevod: "нравиться",
    category: "noun",
    example: "metros como mínimo y visibles",
  },
  {
    word: "cómodo",
    translation: "comfortable",
    perevod: "комфортный",
    category: "adjective",
    example: "Ajuste el asiento para una postura cómoda.",
  },
  {
    word: "competencia",
    translation: "competence/jurisdiction",
    perevod: "компетенция или юрисдикция",
    category: "noun",
    example: "Esta infracción es competencia municipal.",
  },
  {
    word: "competente",
    translation: "competent",
    perevod: "компетентный",
    category: "adjective",
    example: "Acude a la autoridad competente.",
  },
  {
    word: "completamente",
    translation: "completely",
    perevod: "полностью",
    category: "adverb",
    example: "Detén completamente el vehículo en los pasos a nivel.",
  },
  {
    word: "completo",
    translation: "complete/full",
    perevod: "полный",
    category: "adjective",
    example: "Haz una revisión completa",
  },
  {
    word: "comprobar",
    translation: "to check/verify",
    perevod: "проверить",
    category: "verb",
    example: "Comprueba el estado del vehículo",
  },
  {
    word: "comunicar",
    translation: "to communicate",
    perevod: "общаться",
    category: "verb",
    example: "Comunica cualquier cambio de domicilio.",
  },
  {
    word: "conducir",
    translation: "to drive",
    perevod: "водить",
    category: "verb",
    example: "Saber conducir requiere práctica",
  },
  {
    word: "conductor",
    translation: "driver",
    perevod: "водитель",
    category: "noun",
    example: "El conductor debe tener permiso de conducir",
  },
  {
    word: "conductor novel",
    translation: "novice driver",
    perevod: "начинающий водитель",
    category: "noun",
    example: "El conductor novel debe señalizarse.",
  },
  {
    word: "congestión",
    translation: "congestion",
    perevod: "скопление",
    category: "noun",
    example: "La congestión obliga a usar rutas alternativas.",
  },
  {
    word: "constituir",
    translation: "to constitute",
    perevod: "составлять",
    category: "verb",
    example: "Esta acción constituye una infracción grave.",
  },
  {
    word: "continuo",
    translation: "continuous",
    perevod: "непрерывный",
    category: "adjective",
    example: "Línea continua, prohibido adelantar.",
  },
  {
    word: "contrario",
    translation: "opposite/contrary",
    perevod: "противоположный или противоположный",
    category: "adjective",
    example: "No circules en sentido contrario",
  },
  {
    word: "control",
    translation: "control/checkpoint",
    perevod: "контроль",
    category: "noun",
    example: "Hay un control de documentación más adelante.",
  },
  {
    word: "control del tráfico",
    translation: "traffic control",
    perevod: "управление движением",
    category: "noun",
    example: "El control del tráfico es automático.",
  },
  {
    word: "controlar",
    translation: "to control",
    perevod: "контролировать",
    category: "verb",
    example: "Controla siempre tu vehículo",
  },
  {
    word: "convenientemente",
    translation: "conveniently",
    perevod: "удобно",
    category: "adverb",
    example: "La carga debe estar convenientemente asegurada.",
  },
  {
    word: "convoy",
    translation: "convoy",
    perevod: "конвои",
    category: "noun",
    example: "El convoy militar tiene prioridad de paso.",
  },
  {
    word: "correctamente",
    translation: "correctly",
    perevod: "правильно",
    category: "adverb",
    example: "Es necesario colocar correctamente el cinturón de seguridad.",
  },
  {
    word: "correcto",
    translation: "correct/right",
    perevod: "правильно",
    category: "adjective",
    example: "Siga el carril correcto.",
  },
  {
    word: "cruce",
    translation: "intersection/crossing",
    perevod: "пересечение или перекресток",
    category: "noun",
    example: "Cuidado en el cruce de calles",
  },
  {
    word: "cruzar",
    translation: "to cross",
    perevod: "пересечь",
    category: "verb",
    example: "Cruza la calle por el paso de peatones",
  },
  {
    word: "cumplir",
    translation: "to comply with",
    perevod: "соблюдать",
    category: "verb",
    example: "Es obligatorio cumplir con las indicaciones del agente.",
  },
  {
    word: "deben",
    translation: "they must",
    perevod: "они должны",
    category: "verb",
    example:
      "En caso de inmovilización de un vehículo por emergencia, ¿a qué distancia deben colocarse los dispositivos de preseñalización de peligro?",
  },
  {
    word: "deber",
    translation: "must/should",
    perevod: "должен или должен",
    category: "verb",
    example: "Debes respetar las normas",
  },
  {
    word: "debidamente",
    translation: "properly/duly",
    perevod: "правильно или должным образом",
    category: "adverb",
    example: "Toda carga debe estar debidamente asegurada.",
  },
  {
    word: "decreto",
    translation: "decree",
    perevod: "указатель",
    category: "noun",
    example: "El Real Decreto establece las normas básicas.",
  },
  {
    word: "definitivo",
    translation: "definitive/final",
    perevod: "окончательный или окончательный",
    category: "adjective",
    example: "La resolución definitiva tardará dos meses.",
  },
  {
    word: "dejar",
    translation: "to leave/let",
    perevod: "уйти или позволить",
    category: "verb",
    example: "Deja espacio suficiente entre vehículos",
  },
  {
    word: "demostrar",
    translation: "to demonstrate",
    perevod: "продемонстрировать",
    category: "verb",
    example: "Demuestra que conoces las normas.",
  },
  {
    word: "densidad del tráfico",
    translation: "traffic density",
    perevod: "Плотность движения",
    category: "noun",
    example: "La densidad del tráfico es alta.",
  },
  {
    word: "deslumbramiento",
    translation: "glare/dazzling",
    perevod: "блики или ослепительно",
    category: "noun",
    example: "Reduce la velocidad en caso de deslumbramiento.",
  },
  {
    word: "desordenado",
    translation: "disorderly/messy",
    perevod: "беспорядочный или грязный",
    category: "adjective",
    example: "Evite el comportamiento desordenado en la vía.",
  },
  {
    word: "desviar",
    translation: "to detour/divert",
    perevod: "обойти или отвлечься",
    category: "verb",
    example: "Desvía el tráfico si hay obras",
  },
  {
    word: "detectar",
    translation: "to detect",
    perevod: "Чтобы обнаружить",
    category: "verb",
    example: "Detecta los peligros a tiempo",
  },
  {
    word: "detener",
    translation: "to stop/halt",
    perevod: "остановить или остановить",
    category: "verb",
    example: "El agente puede detener el vehículo",
  },
  {
    word: "detenerse",
    translation: "to stop",
    perevod: "чтобы остановиться",
    category: "verb",
    example: "Ante un stop debes detenerse completamente.",
  },
  {
    word: "determinar",
    translation: "to determine",
    perevod: "определить",
    category: "verb",
    example: "El juez determinará la sanción correspondiente.",
  },
  {
    word: "diáfano",
    translation: "transparent/clear",
    perevod: "прозрачный или ясный",
    category: "adjective",
    example: "La superficie acristalada debe permitir la visibilidad diáfana.",
  },
  {
    word: "dimensiones máximas",
    translation: "maximum dimensions",
    perevod: "максимальные размеры",
    category: "noun",
    example: "Las dimensiones máximas están reguladas.",
  },
  {
    word: "dirección",
    translation: "direction/steering",
    perevod: "направление или рулевое управление",
    category: "noun",
    example: "Mantén la dirección correcta",
  },
  {
    word: "directo",
    translation: "direct",
    perevod: "прямой",
    category: "adjective",
    example: "Tome la ruta más directa si es segura.",
  },
  {
    word: "discontinuo",
    translation: "discontinuous",
    perevod: "прерывистый",
    category: "adjective",
    example: "Línea discontinua, adelantamiento permitido.",
  },
  {
    word: "disposición",
    translation: "provision/regulation",
    perevod: "обеспечение или регулирование",
    category: "noun",
    example: "Esta disposición está vigente desde 2003.",
  },
  {
    word: "dispositivo",
    translation: "device",
    perevod: "устройство",
    category: "noun",
    example: "Los dispositivos de seguridad son obligatorios.",
  },
  {
    word: "dispositivo de barrera",
    translation: "barrier device",
    perevod: "Барьерное устройство",
    category: "noun",
    example: "El dispositivo de barrera cierra el paso.",
  },
  {
    word: "dispositivo de preseñalización",
    translation: "warning device",
    perevod: "предупреждающее устройство",
    category: "noun",
    example: "Coloca el dispositivo de preseñalización.",
  },
  {
    word: "distancia",
    translation: "distance",
    perevod: "расстояние",
    category: "noun",
    example:
      "En caso de inmovilización de un vehículo por emergencia, ¿a qué distancia deben colocarse los dispositivos de preseñalización de peligro?",
  },
  {
    word: "distintivo de nacionalidad",
    translation: "nationality badge",
    perevod: "Значок национальности",
    category: "noun",
    example: "El distintivo de nacionalidad es obligatorio.",
  },
  {
    word: "distinto",
    translation: "different/distinct",
    perevod: "разные или отчетливые",
    category: "adjective",
    example: "Cada señal tiene un significado distinto.",
  },
  {
    word: "documento",
    translation: "document",
    perevod: "документ",
    category: "noun",
    example: "Lleva siempre la documentación",
  },
  {
    word: "eficaz",
    translation: "effective/efficient",
    perevod: "эффективно или эффективно",
    category: "adjective",
    example: "Una frenada eficaz es crucial.",
  },
  {
    word: "eficazmente",
    translation: "effectively",
    perevod: "эффективно",
    category: "adverb",
    example: "Debes señalizar eficazmente cualquier obstáculo en la vía.",
  },
  {
    word: "elevado",
    translation: "elevated/high",
    perevod: "повышен или высокий",
    category: "adjective",
    example: "Paso elevado para peatones",
  },
  {
    word: "emergencia",
    translation: "emergency",
    perevod: "чрезвычайная ситуация",
    category: "noun",
    example: "Usa las luces de emergencia si es necesario.",
  },
  {
    word: "encender",
    translation: "to turn on/light",
    perevod: "включить или зажечь",
    category: "verb",
    example: "Enciende las luces si es necesario",
  },
  {
    word: "encendido",
    translation: "on/lit",
    perevod: "на или зажжен",
    category: "adjective",
    example: "Mantén las luces encendidas",
  },
  {
    word: "enlace",
    translation: "junction/link",
    perevod: "соединение или ссылка",
    category: "noun",
    example: "El enlace conecta dos autopistas.",
  },
  {
    word: "entrar",
    translation: "to enter",
    perevod: "чтобы войти",
    category: "verb",
    example: "Entra en la autopista usando el carril de aceleración",
  },
  {
    word: "especial",
    translation: "special",
    perevod: "особенный",
    category: "adjective",
    example: "Precaución especial con niños",
  },
  {
    word: "especialmente",
    translation: "especially",
    perevod: "особенно",
    category: "adverb",
    example: "Conduce con precaución, especialmente en condiciones de lluvia.",
  },
  {
    word: "específico",
    translation: "specific",
    perevod: "специфический",
    category: "adjective",
    example: "Hay normas específicas para motocicletas.",
  },
  {
    word: "esperar",
    translation: "to wait",
    perevod: "чтобы подождать",
    category: "verb",
    example: "Espera a que el semáforo se ponga verde",
  },
  {
    word: "estable",
    translation: "stable",
    perevod: "стабильный",
    category: "adjective",
    example: "Mantenga una velocidad estable.",
  },
  {
    word: "establecer",
    translation: "to establish",
    perevod: "чтобы установить",
    category: "verb",
    example: "Las ordenanzas establecen las normas locales.",
  },
  {
    word: "estacionamiento",
    translation: "parking",
    perevod: "стоянка",
    category: "noun",
    example: "El estacionamiento está prohibido en esta zona.",
  },
  {
    word: "estacionar",
    translation: "to park",
    perevod: "Парк",
    category: "verb",
    example: "No se puede estacionar en doble fila.",
  },
  {
    word: "estacionar",
    translation: "to park",
    perevod: "Парк",
    category: "verb",
    example: "No estaciones en lugares prohibidos.",
  },
  {
    word: "estado",
    translation: "state/condition",
    perevod: "состояние или состояние",
    category: "noun",
    example: "El estado de la carretera influye en la conducción.",
  },
  {
    word: "estrecho",
    translation: "narrow",
    perevod: "узкий",
    category: "adjective",
    example: "Carretera estrecha, precaución",
  },
  {
    word: "eventual",
    translation: "occasional/possible",
    perevod: "случайно или возможно",
    category: "adjective",
    example: "Posible hielo en la calzada",
  },
  {
    word: "excepcional",
    translation: "exceptional",
    perevod: "исключительный",
    category: "adjective",
    example: "Solo en casos excepcionales se permite.",
  },
  {
    word: "excepcionalmente",
    translation: "exceptionally",
    perevod: "исключительно",
    category: "adverb",
    example:
      "Excepcionalmente, se permite circular por el arcén en caso de emergencia.",
  },
  {
    word: "exceptuar",
    translation: "to except",
    perevod: "кроме",
    category: "verb",
    example: "Se exceptúan los vehículos de emergencia.",
  },
  {
    word: "excesivo",
    translation: "excessive",
    perevod: "излишний",
    category: "adjective",
    example: "Velocidad excesiva es peligrosa",
  },
  {
    word: "exento",
    translation: "exempt",
    perevod: "освобождать",
    category: "adjective",
    example: "Los vehículos de emergencia están exentos de algunas normas.",
  },
  {
    word: "expedir",
    translation: "to issue",
    perevod: "выпустить",
    category: "verb",
    example: "La DGT expide los permisos de conducir.",
  },
  {
    word: "expresamente",
    translation: "expressly",
    perevod: "прямо",
    category: "adverb",
    example: "Lo que está expresamente prohibido por las normas.",
  },
  {
    word: "exterior",
    translation: "exterior/outside",
    perevod: "экстерьер или снаружи",
    category: "adjective",
    example: "Limpia los espejos exteriores",
  },
  {
    word: "extinción de incendios",
    translation: "fire fighting",
    perevod: "Огненная борьба",
    category: "noun",
    example: "Vehículo de extinción de incendios.",
  },
  {
    word: "extraordinario",
    translation: "extraordinary",
    perevod: "необычайно",
    category: "adjective",
    example: "Medidas extraordinarias por la nevada.",
  },
  {
    word: "fijo",
    translation: "fixed/stationary",
    perevod: "фиксированный или неподвижный",
    category: "adjective",
    example: "Obstáculo fijo en la vía",
  },
  {
    word: "fluidez del tráfico",
    translation: "traffic flow",
    perevod: "трафик",
    category: "noun",
    example: "Las obras afectan la fluidez del tráfico.",
  },
  {
    word: "frecuente",
    translation: "frequent",
    perevod: "частый",
    category: "adjective",
    example: "Son frecuentes los controles",
  },
  {
    word: "garantizar",
    translation: "to guarantee",
    perevod: "чтобы гарантировать",
    category: "verb",
    example: "Garantiza la seguridad de todos",
  },
  {
    word: "general",
    translation: "general",
    perevod: "общий",
    category: "adjective",
    example: "Esta es la norma general de circulación.",
  },
  {
    word: "generalmente",
    translation: "generally",
    perevod: "в целом",
    category: "adverb",
    example:
      "Generalmente, los límites de velocidad son menores en zonas urbanas.",
  },
  {
    word: "gestión del tráfico",
    translation: "traffic management",
    perevod: "Управление трафиком",
    category: "noun",
    example: "La gestión del tráfico es telemática.",
  },
  {
    word: "girar",
    translation: "to turn",
    perevod: "повернуть",
    category: "verb",
    example: "Indica antes de girar",
  },
  {
    word: "glorieta",
    translation: "roundabout",
    perevod: "кольцевая развязка",
    category: "noun",
    example: "Cede el paso al entrar en la glorieta",
  },
  {
    word: "grave",
    translation: "serious/severe",
    perevod: "серьезный или тяжелый",
    category: "adjective",
    example: "Una infracción grave quita puntos",
  },
  {
    word: "grúa",
    translation: "tow truck",
    perevod: "эвакуатор",
    category: "noun",
    example: "La grúa retirará el vehículo mal aparcado.",
  },
  {
    word: "habitual",
    translation: "usual/habitual",
    perevod: "обычный или привычный",
    category: "adjective",
    example: "Usa tu ruta habitual",
  },
  {
    word: "habitual",
    translation: "usual/habitual",
    perevod: "обычный или привычный",
    category: "adjective",
    example: "Siga su carril habitual a menos que se indique lo contrario.",
  },
  {
    word: "homologado",
    translation: "approved/certified",
    perevod: "утверждено или сертифицировано",
    category: "adjective",
    example: "Solo cascos homologados son válidos.",
  },
  {
    word: "homologar",
    translation: "to approve/certify",
    perevod: "для утверждения или подтверждения",
    category: "verb",
    example: "Todos los cascos deben estar homologados.",
  },
  {
    word: "identificar",
    translation: "to identify",
    perevod: "Чтобы идентифицировать",
    category: "verb",
    example: "Identifica las señales de tráfico",
  },
  {
    word: "igual",
    translation: "same/equal",
    perevod: "то же самое или равный",
    category: "adjective",
    example: "Todos los carriles tienen la misma velocidad máxima.",
  },
  {
    word: "ilegal",
    translation: "illegal",
    perevod: "незаконно",
    category: "adjective",
    example: "Aparcar en doble fila es ilegal",
  },
  {
    word: "implicado",
    translation: "",
    perevod: "",
    category: "adjective",
    example: "En un accidente de tráfico en el que esté implicado",
  },
  {
    word: "imponer",
    translation: "to impose",
    perevod: "навязывать",
    category: "verb",
    example: "Le van a imponer una multa por aparcar mal.",
  },
  {
    word: "incómodo",
    translation: "uncomfortable",
    perevod: "неудобно",
    category: "adjective",
    example: "Una conducción incómoda puede distraer.",
  },
  {
    word: "inconsciente",
    translation: "unconscious",
    perevod: "бессознательный",
    category: "adjective",
    example: "herido está inconsciente",
  },
  {
    word: "incorrecto",
    translation: "incorrect/wrong",
    perevod: "неверно или неправильно",
    category: "adjective",
    example: "Tomar una salida incorrecta puede ser peligroso.",
  },
  {
    word: "indirecto",
    translation: "indirect",
    perevod: "косвенный",
    category: "adjective",
    example: "La luz indirecta puede afectar la visibilidad.",
  },
  {
    word: "ineficaz",
    translation: "ineffective/inefficient",
    perevod: "неэффективный или неэффективный",
    category: "adjective",
    example: "Una señalización ineficaz puede confundir.",
  },
  {
    word: "inestable",
    translation: "unstable",
    perevod: "нестабильный",
    category: "adjective",
    example: "Una carga mal sujeta puede volver el vehículo inestable.",
  },
  {
    word: "inexcusable",
    translation: "inexcusable/mandatory",
    perevod: "непростительно или обязательно",
    category: "adjective",
    example: "Es inexcusable cumplir las normas de tráfico.",
  },
  {
    word: "informar",
    translation: "to inform",
    perevod: "сообщить",
    category: "verb",
    example: "Informa sobre los accidentes a las authorities.",
  },
  {
    word: "infracción",
    translation: "violation/offense",
    perevod: "нарушение или преступление",
    category: "noun",
    example: "Evita cometer infracciones",
  },
  {
    word: "infringir",
    translation: "to infringe/violate",
    perevod: "нарушать или нарушать",
    category: "verb",
    example: "Infringir las normas de tráfico conlleva una sanción.",
  },
  {
    word: "iniciar",
    translation: "to start/begin",
    perevod: "начать или начать",
    category: "verb",
    example: "Inicia la marcha con precaución",
  },
  {
    word: "inmediatamente",
    translation: "immediately",
    perevod: "немедленно",
    category: "adverb",
    example: "Detente inmediatamente ante la señal de stop.",
  },
  {
    word: "inmediato",
    translation: "immediate",
    perevod: "немедленный",
    category: "adjective",
    example: "Aplicación inmediata de la nueva norma.",
  },
  {
    word: "inmediato",
    translation: "immediate",
    perevod: "немедленный",
    category: "adjective",
    example: "Debes detenerte de inmediato cuando te lo indique un agente.",
  },
  {
    word: "inmovilización",
    translation: "immobilization",
    perevod: "иммобилизация",
    category: "noun",
    example: "La inmovilización del vehículo es obligatoria en ese caso.",
  },
  {
    word: "inmovilizar",
    translation: "to immobilize",
    perevod: "иммобилизовать",
    category: "verb",
    example: "El agente puede inmovilizar el vehículo si carece de seguro.",
  },
  {
    word: "innecesario",
    translation: "unnecessary",
    perevod: "ненужный",
    category: "adjective",
    example: "Evita realizar maniobras innecesarias.",
  },
  {
    word: "inseguro",
    translation: "unsafe/insecure",
    perevod: "небезопасно или небезопасно",
    category: "adjective",
    example: "Conducir con neumáticos gastados es inseguro.",
  },
  {
    word: "inspección técnica",
    translation: "technical inspection",
    perevod: "Техническая проверка",
    category: "noun",
    example: "La inspección técnica es obligatoria.",
  },
  {
    word: "inspeccionar",
    translation: "to inspect",
    perevod: "чтобы проверить",
    category: "verb",
    example: "Inspecciona el vehículo antes de viajar.",
  },
  {
    word: "inspector",
    translation: "inspector",
    perevod: "инспектор",
    category: "noun",
    example: "El inspector revisa la documentación.",
  },
  {
    word: "inteligente",
    translation: "smart/intelligent",
    perevod: "умный или умный",
    category: "adjective",
    example: "Un sistema de tráfico inteligente puede reducir atascos.",
  },
  {
    word: "interior",
    translation: "interior/inside",
    perevod: "интерьер или внутри",
    category: "adjective",
    example: "Ajusta el espejo interior",
  },
  {
    word: "interrumpir",
    translation: "to interrupt",
    perevod: "прервать",
    category: "verb",
    example: "No interrumpas el paso de otros vehículos",
  },
  {
    word: "intersección",
    translation: "intersection",
    perevod: "пересечение",
    category: "noun",
    example: "La intersección está regulada por semáforos",
  },
  {
    word: "interurbano",
    translation: "interurban/between cities",
    perevod: "Interurban или между городами",
    category: "adjective",
    example: "En carretera interurbana 90 km/h",
  },
  {
    word: "inválido",
    translation: "invalid",
    perevod: "неверный",
    category: "adjective",
    example: "Un documento inválido no será aceptado.",
  },
  {
    word: "isleta",
    translation: "traffic island",
    perevod: "Остров дорожного движения",
    category: "noun",
    example: "La isleta canaliza el tráfico.",
  },
  {
    word: "itinerario",
    translation: "itinerary/route",
    perevod: "маршрут или маршрут",
    category: "noun",
    example: "Sigue el itinerario señalizado.",
  },
  {
    word: "justificar",
    translation: "to justify",
    perevod: "чтобы оправдать",
    category: "verb",
    example: "Justifica el motivo de tu maniobra.",
  },
  {
    word: "legal",
    translation: "legal",
    perevod: "юридический",
    category: "adjective",
    example: "Asegúrate de que todo sea legal",
  },
  {
    word: "lento",
    translation: "slow",
    perevod: "медленный",
    category: "adjective",
    example: "Ir muy lento también es peligroso",
  },
  {
    word: "leve",
    translation: "minor/light",
    perevod: "несовершеннолетний или свет",
    category: "adjective",
    example: "Una falta leve tiene multa pequeña",
  },
  {
    word: "ligero",
    translation: "light",
    perevod: "свет",
    category: "adjective",
    example: "Vehículo ligero hasta 3500 kg",
  },
  {
    word: "límite",
    translation: "limit",
    perevod: "предел",
    category: "noun",
    example: "Respeta el límite de velocidad establecido.",
  },
  {
    word: "limpio",
    translation: "clean",
    perevod: "чистый",
    category: "adjective",
    example: "Mantenga los cristales limpios para una buena visibilidad.",
  },
  {
    word: "línea de detención",
    translation: "stop line",
    perevod: "Стоп",
    category: "noun",
    example: "Detente antes de la línea de detención.",
  },
  {
    word: "línea longitudinal",
    translation: "longitudinal line",
    perevod: "продольная линия",
    category: "noun",
    example: "La línea longitudinal delimita carriles.",
  },
  {
    word: "luminoso",
    translation: "luminous/bright",
    perevod: "светящийся или яркий",
    category: "adjective",
    example: "Las señales luminosas tienen prioridad sobre las verticales.",
  },
  {
    word: "luz",
    translation: "light",
    perevod: "свет",
    category: "noun",
    example: "Usa las luces cuando sea necesario",
  },
  {
    word: "manifiestamente",
    translation: "manifestly/clearly",
    perevod: "явно или ясно",
    category: "adverb",
    example: "Personas manifiestamente impedidas requieren especial atención.",
  },
  {
    word: "maniobra",
    translation: "maneuver",
    perevod: "маневр",
    category: "noun",
    example: "Realiza la maniobra con precaución",
  },
  {
    word: "mantener",
    translation: "to maintain",
    perevod: "поддерживать",
    category: "verb",
    example: "Mantén la distancia de seguridad",
  },
  {
    word: "marca",
    translation: "marking/sign",
    perevod: "маркировка или знак",
    category: "noun",
    example: "Las marcas viales delimitan los carriles.",
  },
  {
    word: "marca vial",
    translation: "road marking",
    perevod: "дорожная маркировка",
    category: "noun",
    example: "Las marcas viales guían la circulación.",
  },
  {
    word: "masa máxima autorizada",
    translation: "maximum authorized weight",
    perevod: "максимальный уполномоченный вес",
    category: "noun",
    example: "Respeta la masa máxima autorizada.",
  },
  {
    word: "matrícula",
    translation: "license plate/registration",
    perevod: "номерной знак или регистрация",
    category: "noun",
    example: "La matrícula debe estar visible",
  },
  {
    word: "matricular",
    translation: "to register",
    perevod: "для регистрации",
    category: "verb",
    example: "Hay que matricular el vehículo en España.",
  },
  {
    word: "máximo",
    translation: "maximum",
    perevod: "максимум",
    category: "adjective",
    example: "Respeta la velocidad máxima",
  },
  {
    word: "máximo",
    translation: "maximum",
    perevod: "максимум",
    category: "adjective",
    example: "El peso máximo autorizado es de 3500kg.",
  },
  {
    word: "mediana",
    translation: "central reservation",
    perevod: "Центральное резервирование",
    category: "noun",
    example: "No pares en la mediana.",
  },
  {
    word: "mercancías peligrosas",
    translation: "dangerous goods",
    perevod: "Опасные товары",
    category: "noun",
    example: "Transporte especial de mercancías peligrosas.",
  },
  {
    word: "metros",
    translation: "meters",
    perevod: "метры",
    category: "noun",
    example: "metros como mínimo y visibles",
  },
  {
    word: "mínimo",
    translation: "minimum",
    perevod: "минимум",
    category: "adjective",
    example: "Mantén la distancia mínima",
  },
  {
    word: "mínimo",
    translation: "minimum",
    perevod: "минимум",
    category: "adjective",
    example: "Se requiere un nivel mínimo de atención.",
  },
  {
    word: "ministerio",
    translation: "ministry",
    perevod: "министерство",
    category: "noun",
    example: "El Ministerio de Interior regula el tráfico.",
  },
  {
    word: "minusválido",
    translation: "disabled person",
    perevod: "инвалид",
    category: "noun",
    example: "Plaza reservada para minusválido.",
  },
  {
    word: "modificar",
    translation: "to modify",
    perevod: "изменить",
    category: "verb",
    example: "No modifiques el vehículo sin autorización.",
  },
  {
    word: "mostrar",
    translation: "to show",
    perevod: "Показать",
    category: "verb",
    example: "Muestra la documentación si te la piden",
  },
  {
    word: "motocicleta",
    translation: "motorcycle",
    perevod: "мотоцикл",
    category: "noun",
    example: "La motocicleta debe circular por el carril derecho",
  },
  {
    word: "motorizado",
    translation: "motorized",
    perevod: "моторизованный",
    category: "adjective",
    example: "Vehículo motorizado necesita permiso",
  },
  {
    word: "móvil",
    translation: "mobile/moving",
    perevod: "мобильный или движущийся",
    category: "adjective",
    example: "Precaución con obstáculos móviles",
  },
  {
    word: "multa",
    translation: "fine",
    perevod: "отлично",
    category: "noun",
    example: "Te pueden poner una multa por exceso de velocidad",
  },
  {
    word: "necesario",
    translation: "necessary",
    perevod: "необходимый",
    category: "adjective",
    example: "Es necesario llevar la documentación del vehículo.",
  },
  {
    word: "neumático",
    translation: "tire",
    perevod: "шина",
    category: "noun",
    example: "Es importante revisar la presión del neumático.",
  },
  {
    word: "norma",
    translation: "rule/standard",
    perevod: "правило или стандарт",
    category: "noun",
    example: "Las normas de tráfico protegen a todos.",
  },
  {
    word: "normal",
    translation: "normal",
    perevod: "нормальный",
    category: "adjective",
    example: "Condiciones normales de tráfico",
  },
  {
    word: "normalmente",
    translation: "normally",
    perevod: "обычно",
    category: "adverb",
    example: "Normalmente debe circular por el carril derecho.",
  },
  {
    word: "normativa",
    translation: "regulations",
    perevod: "правила",
    category: "noun",
    example: "Cumple la normativa de tráfico",
  },
  {
    word: "notificar",
    translation: "to notify",
    perevod: "Чтобы уведомить",
    category: "verb",
    example: "Te notificarán la sanción por correo.",
  },
  {
    word: "nuevo",
    translation: "new",
    perevod: "новый",
    category: "adjective",
    example: "Este es un nuevo tipo de señal.",
  },
  {
    word: "nunca",
    translation: "never",
    perevod: "никогда",
    category: "adverb",
    example: "Nunca cruces cuando el semáforo está en rojo.",
  },
  {
    word: "obligado",
    translation: "obliged/forced",
    perevod: "обязался или вынужден",
    category: "adjective",
    example: "Estás obligado a detenerte ante un stop.",
  },
  {
    word: "obligar",
    translation: "to obligate/force",
    perevod: "Овертировать или применять",
    category: "verb",
    example: "La ley obliga a usar casco",
  },
  {
    word: "obligatoriamente",
    translation: "mandatorily",
    perevod: "мандатиально",
    category: "adverb",
    example: "Debes usar obligatoriamente el casco en la motocicleta.",
  },
  {
    word: "obligatorio",
    translation: "mandatory/compulsory",
    perevod: "обязательный или обязательный",
    category: "adjective",
    example: "Es obligatorio usar el cinturón",
  },
  {
    word: "observar",
    translation: "to observe",
    perevod: "чтобы наблюдать",
    category: "verb",
    example: "Observa bien antes de cambiar de carril",
  },
  {
    word: "obstaculizar",
    translation: "to obstruct",
    perevod: "Чтобы препятствовать",
    category: "verb",
    example: "No obstaculices el tráfico",
  },
  {
    word: "obstáculo",
    translation: "obstacle",
    perevod: "препятствие",
    category: "noun",
    example: "Evita cualquier obstáculo en la vía",
  },
  {
    word: "obvio",
    translation: "obvious",
    perevod: "очевидный",
    category: "adjective",
    example: "Es obvio que no se puede aparcar aquí.",
  },
  {
    word: "oficial",
    translation: "official",
    perevod: "официальный",
    category: "adjective",
    example: "Consulta solo fuentes oficiales.",
  },
  {
    word: "ordenado",
    translation: "orderly/tidy",
    perevod: "упорядочен или аккуратный",
    category: "adjective",
    example: "El tráfico debe ser ordenado.",
  },
  {
    word: "ordinario",
    translation: "ordinary",
    perevod: "обычный",
    category: "adjective",
    example: "En condiciones ordinarias de tráfico.",
  },
  {
    word: "oscuro",
    translation: "dark",
    perevod: "темный",
    category: "adjective",
    example: "Enciende luces en tiempo oscuro",
  },
  {
    word: "panel de mensaje variable",
    translation: "variable message panel",
    perevod: "Панель сообщений переменной",
    category: "noun",
    example: "El panel de mensaje variable informa del tráfico.",
  },
  {
    word: "parada",
    translation: "stop/bus stop",
    perevod: "остановка или автобусная остановка",
    category: "noun",
    example: "No aparques cerca de una parada de autobús.",
  },
  {
    word: "paralelo",
    translation: "parallel",
    perevod: "параллель",
    category: "adjective",
    example: "Aparca en paralelo a la acera",
  },
  {
    word: "parar",
    translation: "to stop",
    perevod: "чтобы остановиться",
    category: "verb",
    example: "Debes parar en el semáforo rojo",
  },
  {
    word: "parcial",
    translation: "partial",
    perevod: "частично",
    category: "adjective",
    example: "Visibilidad parcial por niebla",
  },
  {
    word: "pasajero",
    translation: "passenger",
    perevod: "пассажир",
    category: "noun",
    example: "Los pasajeros deben usar cinturón",
  },
  {
    word: "paso a nivel",
    translation: "level crossing",
    perevod: "ровная пересечение",
    category: "noun",
    example: "Extrema la precaución en el paso a nivel.",
  },
  {
    word: "paso de peatones",
    translation: "pedestrian crossing",
    perevod: "пешеходный переход",
    category: "noun",
    example: "Cede el paso en el paso de peatones.",
  },
  {
    word: "paso rebajado",
    translation: "lowered crossing",
    perevod: "понижено",
    category: "noun",
    example: "El paso rebajado facilita el acceso.",
  },
  {
    word: "paulatino",
    translation: "gradual",
    perevod: "постепенно",
    category: "adjective",
    example: "La reducción paulatina de la velocidad es más segura.",
  },
  {
    word: "pavimento",
    translation: "pavement",
    perevod: "тротуар",
    category: "noun",
    example: "El pavimento estaba mojado y resbaladizo.",
  },
  {
    word: "peatón",
    translation: "pedestrian",
    perevod: "пешеход",
    category: "noun",
    example: "El peatón tiene prioridad en el paso de cebra",
  },
  {
    word: "peatonal",
    translation: "pedestrian",
    perevod: "пешеход",
    category: "adjective",
    example: "Respeta la zona peatonal",
  },
  {
    word: "peligro",
    translation: "danger",
    perevod: "Опасность",
    category: "noun",
    example: "Señaliza el peligro con el triángulo",
  },
  {
    word: "peligroso",
    translation: "dangerous",
    perevod: "опасный",
    category: "adjective",
    example: "Adelantar aquí es peligroso",
  },
  {
    word: "permanente",
    translation: "permanent",
    perevod: "постоянный",
    category: "adjective",
    example: "Esta es una señal permanente.",
  },
  {
    word: "permiso",
    translation: "license/permit",
    perevod: "лицензия или разрешение",
    category: "noun",
    example: "Necesitas permiso de conducir válido",
  },
  {
    word: "permitido",
    translation: "allowed/permitted",
    perevod: "разрешено или разрешено",
    category: "adjective",
    example: "Está permitido adelantar",
  },
  {
    word: "permitido",
    translation: "allowed/permitted",
    perevod: "разрешено или разрешено",
    category: "adjective",
    example: "El adelantamiento está permitido en esta sección.",
  },
  {
    word: "permitir",
    translation: "to allow/permit",
    perevod: "разрешить или разрешить",
    category: "verb",
    example: "No se permite circular a más de 50 km/h",
  },
  {
    word: "pesado",
    translation: "heavy",
    perevod: "тяжелый",
    category: "adjective",
    example: "Vehículo pesado más de 3500 kg",
  },
  {
    word: "placa de ensayo",
    translation: "test plate",
    perevod: "тестовая пластина",
    category: "noun",
    example: "La placa de ensayo es para vehículos experimentales.",
  },
  {
    word: "pontón trasbordador",
    translation: "ferry bridge",
    perevod: "Паромный мост",
    category: "noun",
    example: "El pontón trasbordador transporta vehículos.",
  },
  {
    word: "posterior",
    translation: "rear/back",
    perevod: "сзади или обратно",
    category: "adjective",
    example: "Mira por el espejo posterior",
  },
  {
    word: "posterior",
    translation: "subsequent/rear",
    perevod: "последующий или задний",
    category: "adjective",
    example: "La revisión posterior es obligatoria.",
  },
  {
    word: "posterior",
    translation: "subsequent/later",
    perevod: "последующий или позже",
    category: "adjective",
    example: "La inspección posterior confirmó los daños.",
  },
  {
    word: "posteriormente",
    translation: "later/afterwards",
    perevod: "позже или после",
    category: "adverb",
    example:
      "Si no llevas la documentación, deberás presentarla posteriormente en la comisaría.",
  },
  {
    word: "prácticamente",
    translation: "practically/virtually",
    perevod: "практически или практически",
    category: "adverb",
    example: "Con niebla densa, la visibilidad es prácticamente nula.",
  },
  {
    word: "prácticamente",
    translation: "practically",
    perevod: "практически",
    category: "adverb",
    example: "Con niebla densa, la visibilidad es prácticamente nula.",
  },
  {
    word: "preceptivo",
    translation: "mandatory/required",
    perevod: "обязательно или требуется",
    category: "adjective",
    example: "Es preceptivo llevar el dispositivo de retención infantil.",
  },
  {
    word: "preseñalización",
    translation: "pre-signaling",
    perevod: "предварительный сигнал",
    category: "noun",
    example: "La preseñalización indica la próxima salida.",
  },
  {
    word: "presentar",
    translation: "to present/show",
    perevod: "представить или показать",
    category: "verb",
    example: "Presenta la documentación cuando te la pidan",
  },
  {
    word: "preventivo",
    translation: "preventive",
    perevod: "профилактическое",
    category: "adjective",
    example: "Se realizan controles de alcoholemia preventivos.",
  },
  {
    word: "previamente",
    translation: "previously/beforehand",
    perevod: "ранее или заранее",
    category: "adverb",
    example:
      "El conductor debe advertir previamente su maniobra con las señales reglamentarias.",
  },
  {
    word: "previo",
    translation: "previous/prior",
    perevod: "предыдущий или ранее",
    category: "adjective",
    example: "Es necesario un examen previo para obtener el permiso.",
  },
  {
    word: "principal",
    translation: "main/principal",
    perevod: "Главный или принципал",
    category: "adjective",
    example: "Circula por la vía principal",
  },
  {
    word: "principal",
    translation: "main/principal",
    perevod: "Главный или принципал",
    category: "adjective",
    example: "La carretera principal tiene preferencia.",
  },
  {
    word: "principalmente",
    translation: "mainly/principally",
    perevod: "в основном или главным образом",
    category: "adverb",
    example: "Debes ser cauteloso principalmente en zonas escolares.",
  },
  {
    word: "prioridad",
    translation: "priority",
    perevod: "приоритет",
    category: "noun",
    example: "Los peatones tienen prioridad",
  },
  {
    word: "prioritario",
    translation: "priority",
    perevod: "приоритет",
    category: "adjective",
    example: "El vehículo de emergencia tiene paso prioritario.",
  },
  {
    word: "privado",
    translation: "private",
    perevod: "частный",
    category: "adjective",
    example: "Propiedad privada, no aparcar",
  },
  {
    word: "procedimiento",
    translation: "procedure",
    perevod: "процедура",
    category: "noun",
    example: "Sigue el procedimiento establecido para recurrir.",
  },
  {
    word: "procurar",
    translation: "to try/ensure",
    perevod: "Чтобы попробовать или убедиться",
    category: "verb",
    example: "Procura mantener la calma al volante",
  },
  {
    word: "prohibido",
    translation: "prohibited/forbidden",
    perevod: "запрещено или запрещено",
    category: "adjective",
    example: "Está prohibido aparcar aquí",
  },
  {
    word: "prohibir",
    translation: "to prohibit/forbid",
    perevod: "запретить или запретить",
    category: "verb",
    example: "Se prohíbe aparcar aquí",
  },
  {
    word: "protección civil",
    translation: "civil protection",
    perevod: "Гражданская защита",
    category: "noun",
    example: "Los servicios de protección civil.",
  },
  {
    word: "provisional",
    translation: "provisional/temporary",
    perevod: "предварительный или временный",
    category: "adjective",
    example: "Permiso provisional hasta recibir el definitivo.",
  },
  {
    word: "prudente",
    translation: "prudent/careful",
    perevod: "разумный или осторожный",
    category: "adjective",
    example: "Conduce de manera prudente",
  },
  {
    word: "público",
    translation: "public",
    perevod: "публичный",
    category: "adjective",
    example: "Respeta el transporte público",
  },
  {
    word: "puente móvil",
    translation: "movable bridge",
    perevod: "подвижный мост",
    category: "noun",
    example: "Espera la señal en el puente móvil.",
  },
  {
    word: "racionalmente",
    translation: "rationally",
    perevod: "рационально",
    category: "adverb",
    example: "Se debe prever racionalmente la irrupción de peatones.",
  },
  {
    word: "ramal",
    translation: "branch/ramp",
    perevod: "ветвь или рампа",
    category: "noun",
    example: "Toma el ramal hacia la ciudad.",
  },
  {
    word: "rápidamente",
    translation: "quickly/rapidly",
    perevod: "быстро или быстро",
    category: "adverb",
    example: "Abandona rápidamente el vehículo en caso de incendio.",
  },
  {
    word: "rápido",
    translation: "fast/quick",
    perevod: "быстро или быстро",
    category: "adjective",
    example: "No seas demasiado rápido",
  },
  {
    word: "realizar",
    translation: "to carry out/perform",
    perevod: "выполнять или выполнять",
    category: "verb",
    example: "Realiza las maniobras con seguridad",
  },
  {
    word: "reanudar",
    translation: "to resume",
    perevod: "возобновить",
    category: "verb",
    example: "Reanuda la marcha cuando sea seguro.",
  },
  {
    word: "rebasar",
    translation: "to exceed/overtake",
    perevod: "превышать или обогнать",
    category: "verb",
    example: "No rebases el límite de velocidad",
  },
  {
    word: "recibir",
    translation: "to receive",
    perevod: "получить",
    category: "verb",
    example: "Recibe las instrucciones del examinador",
  },
  {
    word: "recto",
    translation: "straight",
    perevod: "прямой",
    category: "adjective",
    example: "Sigue recto hasta el semáforo",
  },
  {
    word: "recurrir",
    translation: "to appeal",
    perevod: "апеллировать",
    category: "verb",
    example: "Puedes recurrir la multa si no estás conforme.",
  },
  {
    word: "reducir",
    translation: "to reduce",
    perevod: "чтобы уменьшить",
    category: "verb",
    example: "Reduce la velocidad en curvas",
  },
  {
    word: "reflectante",
    translation: "reflective",
    perevod: "отражающий",
    category: "adjective",
    example: "Es obligatorio llevar un chaleco reflectante en caso de avería.",
  },
  {
    word: "régimen",
    translation: "regime/system",
    perevod: "режим или система",
    category: "noun",
    example: "El régimen sancionador es muy estricto.",
  },
  {
    word: "reglamentario",
    translation: "regulatory/statutory",
    perevod: "нормативно -правовые или установленные законом",
    category: "adjective",
    example: "El uso del casco es reglamentario para motoristas.",
  },
  {
    word: "reglamentario",
    translation: "regulatory",
    perevod: "регаламентный",
    category: "adjective",
    example: "Equipo reglamentario obligatorio en el vehículo.",
  },
  {
    word: "reglamento",
    translation: "regulation",
    perevod: "регулирование",
    category: "noun",
    example: "El reglamento de circulación es de obligado cumplimiento.",
  },
  {
    word: "regulación del tráfico",
    translation: "traffic regulation",
    perevod: "Регламент дорожного движения",
    category: "noun",
    example: "La regulación del tráfico es municipal.",
  },
  {
    word: "regular",
    translation: "to regulate",
    perevod: "регулировать",
    category: "verb",
    example: "Los semáforos regulan el tráfico urbano.",
  },
  {
    word: "remolcar",
    translation: "to tow",
    perevod: "чтобы буксировать",
    category: "verb",
    example: "La grúa va a remolcar el coche averiado.",
  },
  {
    word: "remolque",
    translation: "trailer",
    perevod: "трейлер",
    category: "noun",
    example: "El vehículo tractor arrastra un remolque ligero.",
  },
  {
    word: "repetir",
    translation: "to repeat",
    perevod: "повторить",
    category: "verb",
    example: "No repitas la misma infracción",
  },
  {
    word: "respetar",
    translation: "to respect/obey",
    perevod: "уважать или подчиняться",
    category: "verb",
    example: "Respeta las señales de tráfico",
  },
  {
    word: "responder",
    translation: "to respond",
    perevod: "ответить",
    category: "verb",
    example: "Responde rápido en emergencias",
  },
  {
    word: "responsable",
    translation: "responsible",
    perevod: "ответственный",
    category: "adjective",
    example: "Sé responsable al volante",
  },
  {
    word: "restricciones de circulación",
    translation: "traffic restrictions",
    perevod: "ограничения трафика",
    category: "noun",
    example: "Hay restricciones de circulación por obras.",
  },
  {
    word: "retención",
    translation: "traffic jam",
    perevod: "пробка",
    category: "noun",
    example: "Hay retención de 5 kilómetros.",
  },
  {
    word: "retirar",
    translation: "to withdraw/remove",
    perevod: "Чтобы снять или удалить",
    category: "verb",
    example: "Van a retirar el vehículo mal aparcado.",
  },
  {
    word: "revisión",
    translation: "inspection/review",
    perevod: "осмотр или обзор",
    category: "noun",
    example: "La revisión del vehículo es anual.",
  },
  {
    word: "rotativo",
    translation: "rotating beacon",
    perevod: "вращающийся маяк",
    category: "noun",
    example: "El rotativo naranja señala vehículos especiales.",
  },
  {
    word: "rutinario",
    translation: "routine",
    perevod: "рутинный",
    category: "adjective",
    example: "Un control rutinario de alcoholemia.",
  },
  {
    word: "salir",
    translation: "to exit/leave",
    perevod: "выйти или покинуть",
    category: "verb",
    example: "Sale del carril con cuidado",
  },
  {
    word: "sanción",
    translation: "penalty/sanction",
    perevod: "штраф или санкция",
    category: "noun",
    example: "La sanción puede incluir pérdida de puntos",
  },
  {
    word: "saturación del tráfico",
    translation: "traffic saturation",
    perevod: "насыщение трафика",
    category: "noun",
    example: "La saturación del tráfico causa retrasos.",
  },
  {
    word: "secundario",
    translation: "secondary",
    perevod: "второстепенный",
    category: "adjective",
    example: "Cede paso desde vía secundaria",
  },
  {
    word: "secundario",
    translation: "secondary",
    perevod: "второстепенный",
    category: "adjective",
    example: "Acceda desde una vía secundaria con precaución.",
  },
  {
    word: "seguir",
    translation: "to follow/continue",
    perevod: "следовать или продолжить",
    category: "verb",
    example: "Sigue las indicaciones del agente",
  },
  {
    word: "seguridad",
    translation: "safety/security",
    perevod: "безопасность",
    category: "noun",
    example: "La seguridad vial es fundamental",
  },
  {
    word: "seguro",
    translation: "safe/secure",
    perevod: "безопасно или безопасно",
    category: "adjective",
    example: "Conduce de forma segura",
  },
  {
    word: "seguro",
    translation: "insurance",
    perevod: "страхование",
    category: "noun",
    example: "Es obligatorio tener seguro del vehículo.",
  },
  {
    word: "semáforo",
    translation: "traffic light",
    perevod: "светофор",
    category: "noun",
    example: "Respeta las indicaciones del semáforo.",
  },
  {
    word: "señal",
    translation: "sign/signal",
    perevod: "знак или сигнал",
    category: "noun",
    example: "Respeta todas las señales de tráfico",
  },
  {
    word: "señal acústica",
    translation: "acoustic signal",
    perevod: "акустический сигнал",
    category: "noun",
    example: "La señal acústica es obligatoria.",
  },
  {
    word: "señal luminosa",
    translation: "light signal",
    perevod: "световой сигнал",
    category: "noun",
    example: "La señal luminosa es prioritaria.",
  },
  {
    word: "señalar",
    translation: "to signal/indicate",
    perevod: "сигнализировать или указать",
    category: "verb",
    example: "Señala tus intenciones claramente",
  },
  {
    word: "señalización",
    translation: "signage",
    perevod: "сигнализация",
    category: "noun",
    example: "La señalización vertical indica la velocidad máxima.",
  },
  {
    word: "señalización circunstancial",
    translation: "circumstantial signaling",
    perevod: "ситуационная сигнализация",
    category: "noun",
    example: "La señalización circunstancial es temporal.",
  },
  {
    word: "señalizar",
    translation: "to signpost",
    perevod: "для указателя",
    category: "verb",
    example: "Van a señalizar mejor esta intersección.",
  },
  {
    word: "senda ciclable",
    translation: "cycle path",
    perevod: "велосипедная дорожка",
    category: "noun",
    example: "La senda ciclable es solo para bicicletas.",
  },
  {
    word: "separador",
    translation: "divider",
    perevod: "делитель",
    category: "noun",
    example: "El separador divide los sentidos de circulación.",
  },
  {
    word: "servicio público",
    translation: "public service",
    perevod: "государственная служба",
    category: "noun",
    example: "Vehículo destinado al servicio público.",
  },
  {
    word: "servicio urgente",
    translation: "emergency service",
    perevod: "аварийная служба",
    category: "noun",
    example: "Vehículo en servicio urgente.",
  },
  {
    word: "siempre",
    translation: "always",
    perevod: "всегда",
    category: "adverb",
    example: "Siempre debes respetar las señales de tráfico.",
  },
  {
    word: "simultáneo",
    translation: "simultaneous",
    perevod: "одновременный",
    category: "adjective",
    example: "Control simultáneo de velocidad y documentación.",
  },
  {
    word: "situar",
    translation: "to place/locate",
    perevod: "поместить или найти",
    category: "verb",
    example: "Sitúa el vehículo en el carril correcto",
  },
  {
    word: "solamente",
    translation: "only",
    perevod: "только",
    category: "adverb",
    example:
      "Solamente los vehículos de emergencia pueden exceder el límite de velocidad.",
  },
  {
    word: "sucesivo",
    translation: "successive",
    perevod: "последовательно",
    category: "adjective",
    example: "En controles sucesivos se detectaron más infracciones.",
  },
  {
    word: "sucio",
    translation: "dirty",
    perevod: "грязный",
    category: "adjective",
    example: "Un vehículo sucio puede ocultar la matrícula.",
  },
  {
    word: "suficientemente",
    translation: "sufficiently",
    perevod: "достаточно",
    category: "adverb",
    example:
      "Mantén una distancia suficientemente segura con el vehículo de delante.",
  },
  {
    word: "suspender",
    translation: "to suspend",
    perevod: "Чтобы приостановить",
    category: "verb",
    example: "Pueden suspender el permiso de conducir.",
  },
  {
    word: "sustituir",
    translation: "to replace/substitute",
    perevod: "заменить или заменить",
    category: "verb",
    example: "Sustituye las luces fundidas inmediatamente.",
  },
  {
    word: "taxímetro",
    translation: "taximeter",
    perevod: "таксометр",
    category: "noun",
    example: "El taxímetro calcula el coste del viaje.",
  },
  {
    word: "técnico",
    translation: "technical",
    perevod: "технический",
    category: "adjective",
    example: "La inspección técnica del vehículo es periódica.",
  },
  {
    word: "telepeaje",
    translation: "electronic toll",
    perevod: "Электронный проезд",
    category: "noun",
    example: "El telepeaje acelera el paso por autopistas.",
  },
  {
    word: "temporal",
    translation: "temporary",
    perevod: "временный",
    category: "adjective",
    example: "Hay una señalización temporal por obras.",
  },
  {
    word: "torpe",
    translation: "clumsy/awkward",
    perevod: "неуклюжий или неловкий",
    category: "adjective",
    example: "Una maniobra torpe puede causar un accidente.",
  },
  {
    word: "tráfico",
    translation: "traffic",
    perevod: "трафик",
    category: "noun",
    example: "El tráfico está muy denso esta mañana.",
  },
  {
    word: "tramitar",
    translation: "to process",
    perevod: "для обработки",
    category: "verb",
    example: "Tramita la denuncia en la comisaría.",
  },
  {
    word: "transitar",
    translation: "to transit/travel",
    perevod: "транзит или путешествовать",
    category: "verb",
    example: "Transita con precaución por zonas escolares",
  },
  {
    word: "transporte especial",
    translation: "special transport",
    perevod: "Специальный транспорт",
    category: "noun",
    example: "El transporte especial necesita autorización.",
  },
  {
    word: "travesía",
    translation: "crossing/traverse",
    perevod: "пересечение или проезд",
    category: "noun",
    example: "Reduce la velocidad en travesías urbanas",
  },
  {
    word: "túnel",
    translation: "tunnel",
    perevod: "туннель",
    category: "noun",
    example: "Enciende las luces en el túnel",
  },
  {
    word: "únicamente",
    translation: "only/solely",
    perevod: "только или исключительно",
    category: "adverb",
    example: "Únicamente los vehículos autorizados pueden usar este carril.",
  },
  {
    word: "urbano",
    translation: "urban/city",
    perevod: "городской или город",
    category: "adjective",
    example: "En zona urbana la velocidad es 50 km/h",
  },
  {
    word: "usar",
    translation: "to use",
    perevod: "использовать",
    category: "verb",
    example: "Usa siempre el cinturón de seguridad",
  },
  {
    word: "usuario",
    translation: "user",
    perevod: "пользователь",
    category: "noun",
    example: "Todo usuario de la vía debe cumplir las normas",
  },
  {
    word: "vado",
    translation: "driveway access",
    perevod: "Доступ к дороге",
    category: "noun",
    example: "No obstruyas el vado señalizado.",
  },
  {
    word: "válido",
    translation: "valid",
    perevod: "действительный",
    category: "adjective",
    example: "El permiso de conducir debe estar válido.",
  },
  {
    word: "VAO",
    translation: "high occupancy vehicle",
    perevod: "Высокопроизводительный автомобиль",
    category: "noun",
    example: "Los VAO pueden usar este carril.",
  },
  {
    word: "vehículo",
    translation: "vehicle",
    perevod: "транспортное средство",
    category: "noun",
    example: "El vehículo debe estar matriculado",
  },
  {
    word: "vehículo piloto",
    translation: "pilot vehicle",
    perevod: "пилотный автомобиль",
    category: "noun",
    example: "El vehículo piloto acompaña cargas especiales.",
  },
  {
    word: "velocidad",
    translation: "speed",
    perevod: "скорость",
    category: "noun",
    example: "Respeta los límites de velocidad",
  },
  {
    word: "verificar",
    translation: "to verify",
    perevod: "Чтобы проверить",
    category: "verb",
    example: "Verifica que la documentación esté en regla.",
  },
  {
    word: "vía",
    translation: "road/way",
    perevod: "дорога или путь",
    category: "noun",
    example: "La vía pública es de todos",
  },
  {
    word: "vía de servicio",
    translation: "service road",
    perevod: "сервисная дорога",
    category: "noun",
    example: "La vía de servicio da acceso a los servicios.",
  },
  {
    word: "viejo",
    translation: "old",
    perevod: "старый",
    category: "adjective",
    example: "Un coche viejo puede ser menos seguro.",
  },
  {
    word: "vigente",
    translation: "current/in force",
    perevod: "ток или в силе",
    category: "adjective",
    example: "La normativa vigente es de 2003.",
  },
  {
    word: "vigilancia del tráfico",
    translation: "traffic surveillance",
    perevod: "Наблюдение за дорожным движением",
    category: "noun",
    example: "La vigilancia del tráfico es constante.",
  },
  {
    word: "visibilidad",
    translation: "visibility",
    perevod: "видимость",
    category: "noun",
    example: "La visibilidad era reducida debido a la niebla.",
  },
  {
    word: "visible",
    translation: "visible",
    perevod: "видимый",
    category: "adjective",
    example: "La matrícula debe ser visible",
  },
  {
    word: "visibles",
    translation: "visible",
    perevod: "видимый",
    category: "noun",
    example: "metros como mínimo y visibles",
  },
  {
    word: "vulnerable",
    translation: "vulnerable",
    perevod: "уязвимый",
    category: "adjective",
    example: "Los ciclistas son usuarios vulnerables",
  },
  {
    word: "vulnerar",
    translation: "to violate/breach",
    perevod: "нарушать",
    category: "verb",
    example: "No vulneres la prioridad de paso en las intersecciones.",
  },
  {
    word: "zona",
    translation: "zone/area",
    perevod: "зона",
    category: "noun",
    example: "Esta es una zona de velocidad limitada.",
  },
  {
    word: "zona de carga y descarga",
    translation: "loading and unloading zone",
    perevod: "зона погрузки и разгрузки",
    category: "noun",
    example:
      "Solo vehículos autorizados pueden usar la zona de carga y descarga.",
  },
  {
    word: "zona escolar",
    translation: "school zone",
    perevod: "школьная зона",
    category: "noun",
    example: "En la zona escolar, reduce la velocidad.",
  },
  {
    word: "zona peatonal",
    translation: "pedestrian zone",
    perevod: "пешеходная зона",
    category: "noun",
    example: "No se puede circular por la zona peatonal.",
  },
  {
    word: "zona residencial",
    translation: "residential area",
    perevod: "жилой район",
    category: "noun",
    example: "En zona residencial, la velocidad máxima es 30 km/h.",
  },
  {
    word: "zona urbana",
    translation: "urban area",
    perevod: "городская зона",
    category: "noun",
    example: "En zona urbana, la velocidad máxima es de 50 km/h.",
  },
  {
    word: "zona verde",
    translation: "green zone",
    perevod: "зеленая зона",
    category: "noun",
    example: "La zona verde es para residentes.",
  },
  {
    word: "zona azul",
    translation: "blue zone",
    perevod: "синяя зона",
    category: "noun",
    example: "En la zona azul, debes pagar por aparcar.",
  },
  {
    word: "zona de aparcamiento",
    translation: "parking area",
    perevod: "зона парковки",
    category: "noun",
    example: "Esta es una zona de aparcamiento regulado.",
  },
  {
    word: "zona de obras",
    translation: "construction zone",
    perevod: "зона строительства",
    category: "noun",
    example: "En la zona de obras, reduce la velocidad.",
  },
  {
    word: "zona de peligro",
    translation: "danger zone",
    perevod: "зона опасности",
    category: "noun",
    example: "En la zona de peligro, aumenta la precaución.",
  },
  {
    word: "zona de descanso",
    translation: "rest area",
    perevod: "зона отдыха",
    category: "noun",
    example: "La zona de descanso es ideal para parar y descansar.",
  },
  {
    word: "zona de servicio",
    translation: "service area",
    perevod: "зона обслуживания",
    category: "noun",
    example: "La zona de servicio ofrece combustible y comida.",
  },
  {
    word: "zona de tráfico lento",
    translation: "slow traffic zone",
    perevod: "зона медленного движения",
    category: "noun",
    example: "En la zona de tráfico lento, reduce la velocidad.",
  },
  {
    word: "zona de peligro biológico",
    translation: "biological hazard zone",
    perevod: "зона биологической опасности",
    category: "noun",
    example: "En la zona de peligro biológico, sigue las indicaciones.",
  },
];
